import type { SupportedLanguage } from '../types';

type Copy = Record<SupportedLanguage, string>;
export const CLOUD_SYNC_COPY: Record<string, Copy> = {
  Ready: { en:'Ready', es:'Listo', pt:'Pronto', fr:'Prêt', de:'Bereit', it:'Pronto', ru:'Готово', sv:'Redo' },
  'Ready for manual sync.': { en:'Ready for manual sync.', es:'Listo para sincronizar manualmente.', pt:'Pronto para sincronizar manualmente.', fr:'Prêt pour la synchronisation manuelle.', de:'Bereit zur manuellen Synchronisierung.', it:'Pronto per la sincronizzazione manuale.', ru:'Готово к ручной синхронизации.', sv:'Redo för manuell synkronisering.' },
  'Signed in. Press Sync now to merge this device.': { en:'Signed in. Press Sync now to merge this device.', es:'Sesión iniciada. Pulsa Sincronizar ahora para combinar este dispositivo.', pt:'Login concluído. Pressione Sincronizar agora para combinar este dispositivo.', fr:'Connexion réussie. Appuyez sur Synchroniser maintenant pour fusionner cet appareil.', de:'Angemeldet. Drücke Jetzt synchronisieren, um dieses Gerät zusammenzuführen.', it:'Accesso effettuato. Premi Sincronizza ora per unire questo dispositivo.', ru:'Вход выполнен. Нажмите «Синхронизировать», чтобы объединить данные этого устройства.', sv:'Inloggad. Tryck på Synkronisera nu för att slå ihop den här enheten.' },
  'Press Sync now to merge this device with your cloud progress.': { en:'Press Sync now to merge this device with your cloud progress.', es:'Pulsa Sincronizar ahora para combinar este dispositivo con tu progreso en la nube.', pt:'Pressione Sincronizar agora para combinar este dispositivo com seu progresso na nuvem.', fr:'Appuyez sur Synchroniser maintenant pour fusionner cet appareil avec votre progression cloud.', de:'Drücke Jetzt synchronisieren, um dieses Gerät mit deinem Cloud-Fortschritt zusammenzuführen.', it:'Premi Sincronizza ora per unire questo dispositivo ai progressi nel cloud.', ru:'Нажмите «Синхронизировать», чтобы объединить это устройство с облачным прогрессом.', sv:'Tryck på Synkronisera nu för att slå ihop den här enheten med dina molnframsteg.' },
  'Last sync details': { en:'Last sync details', es:'Detalles de la última sincronización', pt:'Detalhes da última sincronização', fr:'Détails de la dernière synchronisation', de:'Details der letzten Synchronisierung', it:'Dettagli dell’ultima sincronizzazione', ru:'Сведения о последней синхронизации', sv:'Information om senaste synkronisering' },
  Downloaded: { en:'Downloaded', es:'Descargado', pt:'Baixado', fr:'Téléchargé', de:'Heruntergeladen', it:'Scaricati', ru:'Скачано', sv:'Hämtat' },
  'On this device': { en:'On this device', es:'En este dispositivo', pt:'Neste dispositivo', fr:'Sur cet appareil', de:'Auf diesem Gerät', it:'Su questo dispositivo', ru:'На этом устройстве', sv:'På den här enheten' },
  Merged: { en:'Merged', es:'Combinado', pt:'Combinado', fr:'Fusionné', de:'Zusammengeführt', it:'Uniti', ru:'Объединено', sv:'Sammanslaget' },
  'Added to this device': { en:'Added to this device', es:'Añadido a este dispositivo', pt:'Adicionado a este dispositivo', fr:'Ajouté à cet appareil', de:'Diesem Gerät hinzugefügt', it:'Aggiunti a questo dispositivo', ru:'Добавлено на устройство', sv:'Tillagt på den här enheten' },
  'Review schedules updated': { en:'Review schedules updated', es:'Programaciones de Repaso actualizadas', pt:'Agendamentos de Revisão atualizados', fr:'Planifications de Révision mises à jour', de:'Aktualisierte Wiederholungspläne', it:'Programmazioni di Ripasso aggiornate', ru:'Обновлено расписаний Повторения', sv:'Uppdaterade repetitionsscheman' },
  'Review events retained': { en:'Review events retained', es:'Eventos de Repaso conservados', pt:'Eventos de Revisão preservados', fr:'Évaluations de Révision conservées', de:'Behaltene Wiederholungsereignisse', it:'Eventi di Ripasso conservati', ru:'Сохранено событий Повторения', sv:'Bevarade repetitionshändelser' },
  'Images cached locally': { en:'Images cached locally', es:'Imágenes guardadas localmente', pt:'Imagens armazenadas localmente', fr:'Images mises en cache localement', de:'Lokal gespeicherte Bilder', it:'Immagini memorizzate localmente', ru:'Изображений сохранено локально', sv:'Bilder sparade lokalt' },
  Upload: { en:'Upload', es:'Subida', pt:'Envio', fr:'Envoi', de:'Upload', it:'Caricamento', ru:'Отправка', sv:'Uppladdning' },
  'Already current': { en:'Already current', es:'Ya está actualizado', pt:'Já está atualizado', fr:'Déjà à jour', de:'Bereits aktuell', it:'Già aggiornato', ru:'Уже актуально', sv:'Redan aktuellt' },
  'Sync complete': { en:'Sync complete', es:'Sincronización completada', pt:'Sincronização concluída', fr:'Synchronisation terminée', de:'Synchronisierung abgeschlossen', it:'Sincronizzazione completata', ru:'Синхронизация завершена', sv:'Synkronisering klar' },
  downloaded: { en:'downloaded', es:'descargados', pt:'baixados', fr:'téléchargés', de:'heruntergeladen', it:'scaricati', ru:'скачано', sv:'hämtade' },
  merged: { en:'merged', es:'combinados', pt:'combinados', fr:'fusionnés', de:'zusammengeführt', it:'uniti', ru:'объединено', sv:'sammanslagna' },
  'upload confirmed': { en:'upload confirmed', es:'subida confirmada', pt:'envio confirmado', fr:'envoi confirmé', de:'Upload bestätigt', it:'caricamento confermato', ru:'отправка подтверждена', sv:'uppladdning bekräftad' },
  'Downloading cloud progress…': { en:'Downloading cloud progress…', es:'Descargando el progreso de la nube…', pt:'Baixando o progresso da nuvem…', fr:'Téléchargement de la progression cloud…', de:'Cloud-Fortschritt wird heruntergeladen…', it:'Download dei progressi nel cloud…', ru:'Скачивание облачного прогресса…', sv:'Hämtar molnframsteg…' },
  'Merging cloud and device progress…': { en:'Merging cloud and device progress…', es:'Combinando el progreso de la nube y del dispositivo…', pt:'Combinando o progresso da nuvem e do dispositivo…', fr:'Fusion de la progression cloud et de l’appareil…', de:'Cloud- und Gerätefortschritt werden zusammengeführt…', it:'Unione dei progressi cloud e del dispositivo…', ru:'Объединение облачного и локального прогресса…', sv:'Slår ihop moln- och enhetsframsteg…' },
  'Uploading merged progress…': { en:'Uploading merged progress…', es:'Subiendo el progreso combinado…', pt:'Enviando o progresso combinado…', fr:'Envoi de la progression fusionnée…', de:'Zusammengeführter Fortschritt wird hochgeladen…', it:'Caricamento dei progressi uniti…', ru:'Отправка объединённого прогресса…', sv:'Laddar upp sammanslagna framsteg…' },
  'Sync complete. Merged progress uploaded.': { en:'Sync complete. Merged progress uploaded.', es:'Sincronización completada. Se subió el progreso combinado.', pt:'Sincronização concluída. O progresso combinado foi enviado.', fr:'Synchronisation terminée. La progression fusionnée a été envoyée.', de:'Synchronisierung abgeschlossen. Der zusammengeführte Fortschritt wurde hochgeladen.', it:'Sincronizzazione completata. I progressi uniti sono stati caricati.', ru:'Синхронизация завершена. Объединённый прогресс отправлен.', sv:'Synkronisering klar. Sammanslagna framsteg har laddats upp.' },
  'Sync complete. Cloud was already current.': { en:'Sync complete. Cloud was already current.', es:'Sincronización completada. La nube ya estaba actualizada.', pt:'Sincronização concluída. A nuvem já estava atualizada.', fr:'Synchronisation terminée. Le cloud était déjà à jour.', de:'Synchronisierung abgeschlossen. Die Cloud war bereits aktuell.', it:'Sincronizzazione completata. Il cloud era già aggiornato.', ru:'Синхронизация завершена. Облако уже было актуально.', sv:'Synkronisering klar. Molnet var redan aktuellt.' },
};
