import type { CoachPreferences, CoachStyle, ExplanationDepth, SupportedLanguage } from '../types';

export const DEFAULT_COACH_PREFERENCES: CoachPreferences = { style: 'quick', depth: 'normal', askEveryTime: true };
export const COACH_STYLES: CoachStyle[] = ['quick', 'meta', 'elimination', 'deep-geography', 'memory', 'pro-analyst'];
export const EXPLANATION_DEPTHS: ExplanationDepth[] = ['short', 'normal', 'deep'];

export const normalizeCoachPreferences = (value: unknown): CoachPreferences => {
  const source = value && typeof value === 'object' ? value as Partial<CoachPreferences> : {};
  return {
    style: COACH_STYLES.includes(source.style as CoachStyle) ? source.style as CoachStyle : DEFAULT_COACH_PREFERENCES.style,
    depth: EXPLANATION_DEPTHS.includes(source.depth as ExplanationDepth) ? source.depth as ExplanationDepth : DEFAULT_COACH_PREFERENCES.depth,
    askEveryTime: typeof source.askEveryTime === 'boolean' ? source.askEveryTime : DEFAULT_COACH_PREFERENCES.askEveryTime,
  };
};

export const COACH_STYLE_NAMES: Record<CoachStyle, string> = {
  quick: '⚡ Quick Guess', meta: 'Meta Coach', elimination: 'Elimination Coach',
  'deep-geography': 'Deep Geography', memory: 'Memory Coach', 'pro-analyst': 'Pro Analyst',
};

type StyleGuide = { purpose: string; strengths: string; weaknesses: string; best: string; example: string };
type GuideCopy = { intro: string; depth: string; labels: { purpose: string; strengths: string; weaknesses: string; best: string; example: string }; styles: Record<CoachStyle, StyleGuide> };

const en: GuideCopy = {
  intro: 'Style changes how the same visible evidence is weighed and taught. It does not switch automatically.',
  depth: 'Depth changes detail, not the coaching method.',
  labels: { purpose: 'Purpose', strengths: 'Strengths', weaknesses: 'Weaknesses', best: 'Best use', example: 'Example' },
  styles: {
    quick: { purpose: 'A fast second opinion with likely countries, relative likelihood, and a few visible clues.', strengths: 'Fast, scannable, and useful during play.', weaknesses: 'Limited teaching and little causal or memory support.', best: 'When you want an answer without interrupting the round.', example: 'Ireland 55% · UK 25% · dry-stone walls, narrow road · medium confidence.' },
    meta: { purpose: 'Teach GeoGuessr-specific metas, clue roles, strength, reliability, and confusers.', strengths: 'Builds practical clue hierarchy and prevents weak-clue overconfidence.', weaknesses: 'Coverage metas can change and do not always explain the geography.', best: 'No Move study and learning road furniture, plates, poles, signs, or camera clues.', example: 'Dry-stone wall · Tier B · regionifier/confirmer · also Scotland and Wales.' },
    elimination: { purpose: 'Reduce the candidate pool by testing what the scene argues against.', strengths: 'Limits anchoring and teaches comparison under uncertainty.', weaknesses: 'Slower, and most elimination rules have exceptions.', best: 'Ambiguous scenes with several plausible countries.', example: 'Ireland, Scotland, Wales remain; warning-sign shape offers the best split.' },
    'deep-geography': { purpose: 'Explain why visible clues exist through supported geographic and human causes.', strengths: 'Builds causal intuition and durable understanding.', weaknesses: 'Slower and must stop when a causal chain is not supported by the image.', best: 'Study and review of unfamiliar landscapes.', example: 'Rocky fields → cleared stone → livestock boundaries: the field supplied its own fence.' },
    memory: { purpose: 'Turn truthful clues into compact anchors, contrast pairs, and recall prompts.', strengths: 'Improves retention and fits spaced review.', weaknesses: 'Memorable rules can hide exceptions if treated as absolutes.', best: 'After a mistake or when a clue will not stick.', example: 'Anchor: “The field supplied its own fence.” Confuser: Scotland; check warning signs.' },
    'pro-analyst': { purpose: 'Train evidence weighting, contradictions, independence, calibration, and information gain.', strengths: 'Exposes weak assumptions and discourages single-clue anchoring.', weaknesses: 'Slower, less beginner-friendly, and estimates can look falsely precise.', best: 'Advanced analysis of close calls.', example: 'Ireland 48%, UK 31%; moderate stone-wall evidence, generic grass, signs offer highest information gain.' },
  },
};

const localized: Partial<Record<SupportedLanguage, GuideCopy>> = {
  es: { intro: 'El estilo cambia cómo se pondera y enseña la misma evidencia visible. No cambia automáticamente.', depth: 'La profundidad cambia el detalle, no el método.', labels: { purpose: 'Objetivo', strengths: 'Fortalezas', weaknesses: 'Debilidades', best: 'Mejor uso', example: 'Ejemplo' }, styles: {
    quick: { purpose: 'Segunda opinión rápida con países probables, probabilidad relativa y pocas pistas visibles.', strengths: 'Rápido, fácil de leer y útil durante la partida.', weaknesses: 'Enseñanza limitada y poco apoyo causal o de memoria.', best: 'Cuando quieres una respuesta sin interrumpir la ronda.', example: 'Irlanda 55 % · Reino Unido 25 % · muros de piedra, camino estrecho · confianza media.' }, meta: { purpose: 'Enseña metas de GeoGuessr, función, fuerza, fiabilidad y confusores.', strengths: 'Crea jerarquía de pistas y evita sobrevalorar pistas débiles.', weaknesses: 'Las metas de cobertura cambian y no siempre explican la geografía.', best: 'No Move y mobiliario vial, matrículas, postes, señales o cámara.', example: 'Muro de piedra · Nivel B · regional/confirmador · también Escocia y Gales.' }, elimination: { purpose: 'Reduce candidatos comprobando qué contradice la escena.', strengths: 'Evita el anclaje y enseña comparación con incertidumbre.', weaknesses: 'Es más lento y las reglas suelen tener excepciones.', best: 'Escenas ambiguas con varios países plausibles.', example: 'Quedan Irlanda, Escocia y Gales; la forma de las señales los separa mejor.' }, 'deep-geography': { purpose: 'Explica por qué existen las pistas visibles mediante causas geográficas y humanas respaldadas.', strengths: 'Crea intuición causal y comprensión duradera.', weaknesses: 'Más lento; debe detenerse si la imagen no respalda la causa.', best: 'Estudio y repaso de paisajes desconocidos.', example: 'Campo rocoso → piedra retirada → cercado: el campo produjo su propia valla.' }, memory: { purpose: 'Convierte pistas veraces en anclas, contrastes y preguntas de recuerdo.', strengths: 'Mejora la retención y encaja con el repaso espaciado.', weaknesses: 'Las reglas memorables pueden ocultar excepciones.', best: 'Tras un error o cuando una pista no se fija.', example: 'Ancla: «El campo produjo su propia valla». Confusor: Escocia; revisa señales.' }, 'pro-analyst': { purpose: 'Entrena ponderación, contradicciones, independencia, calibración y ganancia de información.', strengths: 'Expone supuestos débiles y evita anclarse en una pista.', weaknesses: 'Más lento, menos accesible y los porcentajes pueden parecer exactos.', best: 'Análisis avanzado de decisiones ajustadas.', example: 'Irlanda 48 %, Reino Unido 31 %; muros moderados, hierba genérica; las señales informan más.' },
  } },
  pt: { intro: 'O estilo muda como a mesma evidência visível é ponderada e ensinada. Não muda automaticamente.', depth: 'A profundidade muda o detalhe, não o método.', labels: { purpose: 'Objetivo', strengths: 'Pontos fortes', weaknesses: 'Pontos fracos', best: 'Melhor uso', example: 'Exemplo' }, styles: {
    quick: { purpose: 'Segunda opinião rápida com países prováveis, estimativas relativas e poucas pistas visíveis.', strengths: 'Rápido, fácil de ler e útil durante o jogo.', weaknesses: 'Ensino limitado e pouco apoio causal ou de memória.', best: 'Quando quer uma resposta sem interromper a rodada.', example: 'Irlanda 55% · Reino Unido 25% · muros de pedra, estrada estreita · confiança média.' }, meta: { purpose: 'Ensina metas, função, força, confiabilidade e países confundíveis.', strengths: 'Cria hierarquia prática e evita supervalorizar pistas fracas.', weaknesses: 'Metas de cobertura mudam e nem sempre explicam a geografia.', best: 'No Move e estudo de balizadores, placas, postes, sinais ou câmera.', example: 'Muro de pedra · Nível B · regional/confirmador · também Escócia e País de Gales.' }, elimination: { purpose: 'Reduz candidatos testando o que a cena desfavorece.', strengths: 'Evita ancoragem e ensina comparação sob incerteza.', weaknesses: 'É mais lento e regras de eliminação têm exceções.', best: 'Cenas ambíguas com vários países plausíveis.', example: 'Irlanda, Escócia e Gales restam; o formato dos sinais separa melhor.' }, 'deep-geography': { purpose: 'Explica por que as pistas existem usando causas geográficas e humanas sustentadas.', strengths: 'Constrói intuição causal e entendimento duradouro.', weaknesses: 'Mais lento; deve parar quando a imagem não sustenta a causa.', best: 'Estudo e revisão de paisagens desconhecidas.', example: 'Campo rochoso → pedra retirada → cercas: o campo forneceu a própria cerca.' }, memory: { purpose: 'Transforma pistas verdadeiras em âncoras, contrastes e perguntas de memória.', strengths: 'Melhora retenção e combina com revisão espaçada.', weaknesses: 'Regras memoráveis podem esconder exceções.', best: 'Depois de um erro ou quando uma pista não fixa.', example: 'Âncora: “O campo forneceu a própria cerca”. Confusor: Escócia; veja os sinais.' }, 'pro-analyst': { purpose: 'Treina pesos, contradições, independência, calibração e ganho de informação.', strengths: 'Expõe suposições fracas e evita ancoragem em uma pista.', weaknesses: 'Mais lento; percentuais podem parecer precisos demais.', best: 'Análise avançada de decisões apertadas.', example: 'Irlanda 48%, Reino Unido 31%; muros moderados, grama genérica; sinais informam mais.' },
  } },
  fr: { intro: 'Le style change la pondération et l’enseignement des mêmes indices visibles. Il ne change jamais automatiquement.', depth: 'La profondeur change le détail, pas la méthode.', labels: { purpose: 'But', strengths: 'Points forts', weaknesses: 'Limites', best: 'Usage conseillé', example: 'Exemple' }, styles: {
    quick: { purpose: 'Un second avis rapide avec pays probables, vraisemblance relative et quelques indices.', strengths: 'Rapide, lisible et utile en partie.', weaknesses: 'Peu d’enseignement causal ou mnémotechnique.', best: 'Obtenir une réponse sans interrompre la manche.', example: 'Irlande 55 % · Royaume-Uni 25 % · murs de pierre, route étroite · confiance moyenne.' }, meta: { purpose: 'Enseigne les métas, leur rôle, force, fiabilité et les confusions.', strengths: 'Hiérarchise les indices et évite de surévaluer les faibles.', weaknesses: 'Les métas de couverture changent et n’expliquent pas toujours la géographie.', best: 'No Move et mobilier routier, plaques, poteaux, panneaux ou caméra.', example: 'Mur de pierre · Niveau B · régional/confirmation · aussi Écosse et pays de Galles.' }, elimination: { purpose: 'Réduit les candidats en testant ce que la scène contredit.', strengths: 'Évite l’ancrage et apprend la comparaison incertaine.', weaknesses: 'Plus lent ; les règles ont souvent des exceptions.', best: 'Scènes ambiguës avec plusieurs pays plausibles.', example: 'Irlande, Écosse et Galles restent ; la forme des panneaux les sépare le mieux.' }, 'deep-geography': { purpose: 'Explique pourquoi les indices existent par des causes géographiques et humaines étayées.', strengths: 'Construit une intuition causale durable.', weaknesses: 'Plus lent ; doit s’arrêter si l’image ne soutient pas la cause.', best: 'Étude et révision de paysages inconnus.', example: 'Champ rocheux → pierres retirées → clôtures : le champ fournit sa propre clôture.' }, memory: { purpose: 'Transforme les indices fiables en repères, contrastes et questions de rappel.', strengths: 'Améliore la mémorisation et la révision espacée.', weaknesses: 'Une règle mémorable peut masquer des exceptions.', best: 'Après une erreur ou pour un indice difficile à retenir.', example: 'Repère : « Le champ fournit sa propre clôture ». Confusion : Écosse ; vérifier les panneaux.' }, 'pro-analyst': { purpose: 'Entraîne pondération, contradictions, indépendance, calibration et gain d’information.', strengths: 'Révèle les hypothèses faibles et limite l’ancrage.', weaknesses: 'Plus lent ; les pourcentages peuvent sembler trop précis.', best: 'Analyse avancée des décisions serrées.', example: 'Irlande 48 %, Royaume-Uni 31 % ; murs modérés, herbe générique ; panneaux plus informatifs.' },
  } },
  de: { intro: 'Der Stil verändert, wie dieselben sichtbaren Hinweise gewichtet und erklärt werden. Er wechselt nie automatisch.', depth: 'Die Tiefe verändert Details, nicht die Methode.', labels: { purpose: 'Zweck', strengths: 'Stärken', weaknesses: 'Schwächen', best: 'Bester Einsatz', example: 'Beispiel' }, styles: {
    quick: { purpose: 'Schnelle Zweitmeinung mit Ländern, relativer Einschätzung und wenigen sichtbaren Hinweisen.', strengths: 'Schnell, übersichtlich und im Spiel nützlich.', weaknesses: 'Begrenzter Lern- und Erinnerungseffekt.', best: 'Wenn die Runde nicht unterbrochen werden soll.', example: 'Irland 55 % · Vereinigtes Königreich 25 % · Steinmauern, schmale Straße · mittlere Sicherheit.' }, meta: { purpose: 'Lehrt GeoGuessr-Metas, Rolle, Stärke, Zuverlässigkeit und Verwechslungen.', strengths: 'Baut Hinweis-Hierarchie auf und bremst schwache Indizien.', weaknesses: 'Abdeckungs-Metas ändern sich und erklären Geografie nicht immer.', best: 'No Move sowie Leitpfosten, Kennzeichen, Masten, Schilder und Kamera.', example: 'Steinmauer · Stufe B · regional/bestätigend · auch Schottland und Wales.' }, elimination: { purpose: 'Verkleinert den Kandidatenkreis anhand widersprechender Merkmale.', strengths: 'Verhindert frühe Festlegung und lehrt Vergleiche.', weaknesses: 'Langsamer; Ausschlussregeln haben Ausnahmen.', best: 'Mehrdeutige Szenen mit mehreren Ländern.', example: 'Irland, Schottland und Wales bleiben; Warnschilder trennen sie am besten.' }, 'deep-geography': { purpose: 'Erklärt Hinweise durch belegte geografische und menschliche Ursachen.', strengths: 'Schafft dauerhaftes kausales Verständnis.', weaknesses: 'Langsamer; stoppt bei unzureichender Bildgrundlage.', best: 'Lernen und Wiederholen unbekannter Landschaften.', example: 'Steiniger Acker → Steine räumen → Grenzen: Das Feld liefert seinen eigenen Zaun.' }, memory: { purpose: 'Macht aus wahren Hinweisen Merksätze, Kontraste und Abruffragen.', strengths: 'Verbessert Behalten und Wiederholung.', weaknesses: 'Merksätze können Ausnahmen verdecken.', best: 'Nach Fehlern oder bei schwer merkbaren Hinweisen.', example: 'Merksatz: „Das Feld liefert seinen eigenen Zaun.“ Verwechslung: Schottland; Schilder prüfen.' }, 'pro-analyst': { purpose: 'Trainiert Gewichtung, Widersprüche, Unabhängigkeit, Kalibrierung und Informationsgewinn.', strengths: 'Zeigt schwache Annahmen und verhindert Einzelhinweis-Anker.', weaknesses: 'Langsamer; Prozentwerte wirken leicht zu genau.', best: 'Fortgeschrittene Analyse knapper Fälle.', example: 'Irland 48 %, UK 31 %; Mauern mittel, Gras allgemein; Schilder liefern mehr Information.' },
  } },
  it: { intro: 'Lo stile cambia come le stesse prove visibili vengono pesate e insegnate. Non cambia automaticamente.', depth: 'La profondità cambia il dettaglio, non il metodo.', labels: { purpose: 'Scopo', strengths: 'Punti di forza', weaknesses: 'Limiti', best: 'Uso ideale', example: 'Esempio' }, styles: {
    quick: { purpose: 'Secondo parere rapido con paesi probabili, stime relative e pochi indizi visibili.', strengths: 'Rapido, leggibile e utile durante il gioco.', weaknesses: 'Insegnamento causale e memoria limitati.', best: 'Quando vuoi una risposta senza interrompere il turno.', example: 'Irlanda 55% · Regno Unito 25% · muri a secco, strada stretta · confidenza media.' }, meta: { purpose: 'Insegna meta, ruolo, forza, affidabilità e paesi confondibili.', strengths: 'Crea una gerarchia pratica e limita gli indizi deboli.', weaknesses: 'Le meta di copertura cambiano e non spiegano sempre la geografia.', best: 'No Move e studio di delineatori, targhe, pali, segnali o camera.', example: 'Muro a secco · Livello B · regionale/conferma · anche Scozia e Galles.' }, elimination: { purpose: 'Riduce i candidati verificando ciò che la scena contraddice.', strengths: 'Evita l’ancoraggio e insegna il confronto incerto.', weaknesses: 'Più lento; le regole hanno eccezioni.', best: 'Scene ambigue con più paesi plausibili.', example: 'Restano Irlanda, Scozia e Galles; la forma dei segnali li separa meglio.' }, 'deep-geography': { purpose: 'Spiega perché esistono gli indizi con cause geografiche e umane supportate.', strengths: 'Costruisce intuizione causale duratura.', weaknesses: 'Più lento; si ferma se l’immagine non sostiene la causa.', best: 'Studio e ripasso di paesaggi sconosciuti.', example: 'Campo roccioso → pietre rimosse → recinti: il campo fornisce la propria recinzione.' }, memory: { purpose: 'Trasforma indizi veri in ancore, contrasti e domande di richiamo.', strengths: 'Migliora memoria e ripasso dilazionato.', weaknesses: 'Le regole memorabili possono nascondere eccezioni.', best: 'Dopo un errore o con un indizio difficile.', example: 'Ancora: «Il campo fornisce la propria recinzione». Confusore: Scozia; controlla i segnali.' }, 'pro-analyst': { purpose: 'Allena pesi, contraddizioni, indipendenza, calibrazione e guadagno informativo.', strengths: 'Espone ipotesi deboli ed evita un solo indizio dominante.', weaknesses: 'Più lento; le percentuali possono sembrare troppo precise.', best: 'Analisi avanzata di casi ravvicinati.', example: 'Irlanda 48%, UK 31%; muri moderati, erba generica; i segnali informano di più.' },
  } },
  ru: { intro: 'Стиль меняет взвешивание и объяснение одних и тех же видимых признаков. Автопереключения нет.', depth: 'Глубина меняет детализацию, а не метод.', labels: { purpose: 'Цель', strengths: 'Сильные стороны', weaknesses: 'Слабые стороны', best: 'Лучшее применение', example: 'Пример' }, styles: {
    quick: { purpose: 'Быстрое второе мнение: вероятные страны, относительные оценки и несколько признаков.', strengths: 'Быстро читается и удобно во время игры.', weaknesses: 'Мало обучения, причинных связей и поддержки памяти.', best: 'Когда нужен ответ без остановки раунда.', example: 'Ирландия 55% · Великобритания 25% · каменные стены, узкая дорога · средняя уверенность.' }, meta: { purpose: 'Учит метам GeoGuessr, их роли, силе, надёжности и похожим странам.', strengths: 'Строит иерархию признаков и не даёт переоценивать слабые.', weaknesses: 'Меты покрытия меняются и не всегда объясняют географию.', best: 'No Move, столбики, номера, опоры, знаки и камера.', example: 'Каменная стена · Уровень B · регион/подтверждение · также Шотландия и Уэльс.' }, elimination: { purpose: 'Сужает круг стран по признакам, которые противоречат сцене.', strengths: 'Снижает раннее заякоривание и учит сравнению.', weaknesses: 'Медленнее; правила исключения имеют исключения.', best: 'Неоднозначные сцены с несколькими странами.', example: 'Остаются Ирландия, Шотландия и Уэльс; лучше всего разделят предупреждающие знаки.' }, 'deep-geography': { purpose: 'Объясняет происхождение признаков только подтверждёнными географическими и человеческими причинами.', strengths: 'Создаёт устойчивое причинное понимание.', weaknesses: 'Медленнее; останавливается при нехватке данных.', best: 'Изучение и повторение незнакомых ландшафтов.', example: 'Каменистое поле → уборка камней → ограды: поле даёт материал для собственного забора.' }, memory: { purpose: 'Превращает правдивые признаки в якоря, контрасты и вопросы для вспоминания.', strengths: 'Улучшает запоминание и интервальное повторение.', weaknesses: 'Яркие правила могут скрывать исключения.', best: 'После ошибки или для трудного признака.', example: 'Якорь: «Поле само дало забор». Путаница: Шотландия; проверить знаки.' }, 'pro-analyst': { purpose: 'Тренирует веса, противоречия, независимость, калибровку и прирост информации.', strengths: 'Показывает слабые допущения и не даёт заякориться на одном признаке.', weaknesses: 'Медленнее; проценты могут казаться излишне точными.', best: 'Продвинутый разбор близких вариантов.', example: 'Ирландия 48%, UK 31%; стены — средний признак, трава — общий; знаки информативнее.' },
  } },
  sv: { intro: 'Stilen ändrar hur samma synliga bevis vägs och lärs ut. Den byts aldrig automatiskt.', depth: 'Djup ändrar detaljnivån, inte metoden.', labels: { purpose: 'Syfte', strengths: 'Styrkor', weaknesses: 'Svagheter', best: 'Bäst för', example: 'Exempel' }, styles: {
    quick: { purpose: 'Snabb andra bedömning med troliga länder, relativa uppskattningar och få synliga ledtrådar.', strengths: 'Snabb, lättläst och bra under spel.', weaknesses: 'Begränsad undervisning och minneshjälp.', best: 'När du vill ha svar utan att avbryta rundan.', example: 'Irland 55 % · Storbritannien 25 % · stenmurar, smal väg · medelhög säkerhet.' }, meta: { purpose: 'Lär ut GeoGuessr-meta, roll, styrka, tillförlitlighet och förväxlingsländer.', strengths: 'Bygger ledtrådshierarki och motverkar svaga slutsatser.', weaknesses: 'Täckningsmeta ändras och förklarar inte alltid geografin.', best: 'No Move samt pollare, skyltar, stolpar, plåtar och kamerameta.', example: 'Stenmur · Nivå B · regional/bekräftande · även Skottland och Wales.' }, elimination: { purpose: 'Minskar kandidatfältet genom att pröva vad scenen talar emot.', strengths: 'Motverkar tidig låsning och lär ut jämförelse.', weaknesses: 'Långsammare; regler har ofta undantag.', best: 'Tvetydiga scener med flera rimliga länder.', example: 'Irland, Skottland och Wales återstår; varningsskyltar skiljer bäst.' }, 'deep-geography': { purpose: 'Förklarar varför ledtrådar finns med stödda geografiska och mänskliga orsaker.', strengths: 'Bygger hållbar kausal förståelse.', weaknesses: 'Långsammare; stannar när bilden inte stöder orsaken.', best: 'Studier och repetition av okända landskap.', example: 'Stenig åker → borttagna stenar → gränser: fältet gav material till sitt eget staket.' }, memory: { purpose: 'Gör sanna ledtrådar till minnesankare, kontraster och återkallningsfrågor.', strengths: 'Förbättrar minne och intervallträning.', weaknesses: 'Minnesregler kan dölja undantag.', best: 'Efter ett misstag eller för svåra ledtrådar.', example: 'Ankare: ”Fältet gav sitt eget staket.” Förväxling: Skottland; kontrollera skyltar.' }, 'pro-analyst': { purpose: 'Tränar viktning, motsägelser, oberoende, kalibrering och informationsvinst.', strengths: 'Visar svaga antaganden och motverkar enskild ledtrådslåsning.', weaknesses: 'Långsammare; procent kan se alltför exakta ut.', best: 'Avancerad analys av jämna fall.', example: 'Irland 48 %, UK 31 %; murar måttliga, gräs generiskt; skyltar ger mest information.' },
  } },
};

export const coachGuide = (language: SupportedLanguage) => localized[language] || en;
