import type { SupportedLanguage } from '../types';

type CountryTargetCopy = {
  tab: string; title: string; description: string; defaultFloor: string; country: string; choose: string; floor: string;
  add: string; update: string; edit: string; remove: string; empty: string; reset: string;
};
export const COUNTRY_TARGET_COPY: Record<SupportedLanguage, CountryTargetCopy> = {
  en: { tab: 'Preferences', title: 'Country score targets', description: 'Set higher score targets for your specializations. In Play and Review, a wrong country or a score below your target counts as a mistake. Existing stricter rules still apply; points stay unchanged.', defaultFloor: 'Default minimum score', country: 'Country', choose: 'Choose a country', floor: 'Minimum score', add: 'Add target', update: 'Update target', edit: 'Edit target', remove: 'Remove target', empty: 'No country targets yet. Countries use the default minimum score.', reset: 'Use scheduling default' },
  es: { tab: 'Preferencias', title: 'Objetivos de puntuación por país', description: 'Establece objetivos más altos para tus especializaciones. En juego y repaso, un país incorrecto o una puntuación inferior al objetivo cuenta como error. Las reglas más estrictas siguen vigentes; los puntos no cambian.', defaultFloor: 'Puntuación mínima predeterminada', country: 'País', choose: 'Elige un país', floor: 'Puntuación mínima', add: 'Añadir objetivo', update: 'Actualizar objetivo', edit: 'Editar objetivo', remove: 'Eliminar objetivo', empty: 'Aún no hay objetivos por país. Se usa la puntuación mínima predeterminada.', reset: 'Usar valor de programación' },
  pt: { tab: 'Preferências', title: 'Metas de pontuação por país', description: 'Defina metas mais altas para suas especializações. No jogo e na revisão, errar o país ou ficar abaixo da meta conta como erro. Regras mais rigorosas continuam valendo; os pontos não mudam.', defaultFloor: 'Pontuação mínima padrão', country: 'País', choose: 'Escolha um país', floor: 'Pontuação mínima', add: 'Adicionar meta', update: 'Atualizar meta', edit: 'Editar meta', remove: 'Remover meta', empty: 'Nenhuma meta por país. Os países usam a pontuação mínima padrão.', reset: 'Usar padrão de agendamento' },
  fr: { tab: 'Préférences', title: 'Objectifs de score par pays', description: 'Définissez des objectifs plus élevés pour vos spécialisations. En jeu et en révision, un mauvais pays ou un score inférieur à votre objectif compte comme une erreur. Les règles plus strictes restent actives ; les points ne changent pas.', defaultFloor: 'Score minimum par défaut', country: 'Pays', choose: 'Choisir un pays', floor: 'Score minimum', add: 'Ajouter un objectif', update: 'Modifier l’objectif', edit: 'Modifier l’objectif', remove: 'Supprimer l’objectif', empty: 'Aucun objectif par pays. Les pays utilisent le score minimum par défaut.', reset: 'Utiliser le seuil de planification' },
  de: { tab: 'Präferenzen', title: 'Punkteziele pro Land', description: 'Lege höhere Ziele für deine Spezialisierungen fest. Im Spiel und bei Wiederholungen zählen ein falsches Land oder Punkte unter deinem Ziel als Fehler. Strengere Regeln gelten weiterhin; die Punkte bleiben unverändert.', defaultFloor: 'Standard-Mindestpunktzahl', country: 'Land', choose: 'Land auswählen', floor: 'Mindestpunktzahl', add: 'Ziel hinzufügen', update: 'Ziel aktualisieren', edit: 'Ziel bearbeiten', remove: 'Ziel entfernen', empty: 'Noch keine Länderziele. Es gilt die Standard-Mindestpunktzahl.', reset: 'Planungsstandard verwenden' },
  it: { tab: 'Preferenze', title: 'Obiettivi di punteggio per paese', description: 'Imposta obiettivi più alti per le tue specializzazioni. Nel gioco e nel ripasso, un paese sbagliato o un punteggio sotto il tuo obiettivo conta come errore. Le regole più rigorose restano attive; i punti non cambiano.', defaultFloor: 'Punteggio minimo predefinito', country: 'Paese', choose: 'Scegli un paese', floor: 'Punteggio minimo', add: 'Aggiungi obiettivo', update: 'Aggiorna obiettivo', edit: 'Modifica obiettivo', remove: 'Rimuovi obiettivo', empty: 'Nessun obiettivo per paese. Si usa il punteggio minimo predefinito.', reset: 'Usa il valore di pianificazione' },
  ru: { tab: 'Предпочтения', title: 'Целевые баллы по странам', description: 'Задайте более высокие цели для специализации. В игре и повторении неверная страна или балл ниже вашей цели считается ошибкой. Более строгие правила продолжают действовать; набранные очки не меняются.', defaultFloor: 'Минимальный балл по умолчанию', country: 'Страна', choose: 'Выберите страну', floor: 'Минимальный балл', add: 'Добавить цель', update: 'Обновить цель', edit: 'Изменить цель', remove: 'Удалить цель', empty: 'Целей по странам пока нет. Используется минимальный балл по умолчанию.', reset: 'Использовать порог расписания' },
  sv: { tab: 'Preferenser', title: 'Poängmål per land', description: 'Sätt högre poängmål för dina specialiseringar. I spel och repetition räknas fel land eller poäng under ditt mål som ett misstag. Strängare regler gäller fortfarande; poängen ändras inte.', defaultFloor: 'Standard för lägsta poäng', country: 'Land', choose: 'Välj ett land', floor: 'Lägsta poäng', add: 'Lägg till mål', update: 'Uppdatera mål', edit: 'Redigera mål', remove: 'Ta bort mål', empty: 'Inga mål per land ännu. Länder använder standardgränsen.', reset: 'Använd schemaläggningens standard' },
};
