import type { SupportedLanguage } from '../types';

export const LOCATION_CARD_COPY: Record<string, Record<SupportedLanguage, string>> = {
  resolvingLocation: { en: 'Resolving exact location...', es: 'Resolviendo la ubicación exacta...', pt: 'Resolvendo a localização exata...', fr: 'Localisation exacte en cours…', de: 'Genauer Ort wird ermittelt …', it: 'Ricerca della posizione esatta...', ru: 'Определение точного места…', sv: 'Bestämmer exakt plats…' },
  addressUnavailable: { en: 'Exact address details not available for this rural road point.', es: 'No hay detalles exactos de dirección para este punto rural.', pt: 'Detalhes exatos do endereço não estão disponíveis para este ponto rural.', fr: 'Les détails exacts ne sont pas disponibles pour ce point rural.', de: 'Für diesen ländlichen Punkt sind keine genauen Adressdaten verfügbar.', it: 'Dettagli esatti non disponibili per questo punto rurale.', ru: 'Точные данные адреса для этой сельской точки недоступны.', sv: 'Exakta adressuppgifter saknas för denna landsbygdspunkt.' },
  saveForReview: { en: 'Save this location for Review', es: 'Guardar este lugar para repasar', pt: 'Salvar este local para revisão', fr: 'Enregistrer ce lieu pour révision', de: 'Diesen Ort zur Wiederholung speichern', it: 'Salva questo luogo per il ripasso', ru: 'Сохранить место для повторения', sv: 'Spara platsen för repetition' },
  reviewSaveFailed: { en: 'Could not save. Try again.', es: 'No se pudo guardar. Inténtalo de nuevo.', pt: 'Não foi possível salvar. Tente novamente.', fr: 'Impossible d’enregistrer. Réessayez.', de: 'Speichern fehlgeschlagen. Versuche es erneut.', it: 'Impossibile salvare. Riprova.', ru: 'Не удалось сохранить. Повторите попытку.', sv: 'Det gick inte att spara. Försök igen.' },
  savedForReview: { en: 'Saved for Review ✓', es: 'Guardado para repasar ✓', pt: 'Salvo para revisão ✓', fr: 'Enregistré pour révision ✓', de: 'Zur Wiederholung gespeichert ✓', it: 'Salvato per il ripasso ✓', ru: 'Сохранено для повторения ✓', sv: 'Sparad för repetition ✓' },
  copyCoords: { en: 'Copy coords', es: 'Copiar coordenadas', pt: 'Copiar coordenadas', fr: 'Copier les coordonnées', de: 'Koordinaten kopieren', it: 'Copia coordinate', ru: 'Копировать координаты', sv: 'Kopiera koordinater' },
  copied: { en: 'Copied', es: 'Copiado', pt: 'Copiado', fr: 'Copié', de: 'Kopiert', it: 'Copiato', ru: 'Скопировано', sv: 'Kopierat' },
};
