import countryCatalog from '../../../src/data/countryCatalog.json' with { type: 'json' };
import hintsData from '../../../server/data/geoguessr-hints.json' with { type: 'json' };
import geometasData from '../../../server/data/geometas-hints.json' with { type: 'json' };

type Mode = 'hints' | 'analyze' | 'analyze360' | 'explain' | 'cards' | 'clue' | 'clue-safe';
type Style = 'quick' | 'meta' | 'elimination' | 'deep-geography' | 'memory' | 'pro-analyst'; type Depth = 'short' | 'normal' | 'deep';
type Frame = { mimeType: string; imageData: string };
type KeyState = { key: string; cooldownUntil: number };
const modes = new Set<Mode>(['hints', 'analyze', 'analyze360', 'explain', 'cards', 'clue', 'clue-safe']);
const languages: Record<string, string> = { en: 'English', es: 'Spanish', pt: 'Portuguese', fr: 'French', de: 'German', it: 'Italian', ru: 'Russian', sv: 'Swedish' };
const styles: Record<Style, string> = { quick: 'QUICK GUESS: put a short conclusion in description and 2–5 strongest visible clues in strongClues; concise rankings and no long lesson.', meta: 'META COACH: put the verdict in description; formatted tier, role, and reliability in strongClues; limits in weakClues; confusers in confusions; next meta in nextThingsToInspect.', elimination: 'ELIMINATION COACH: put the candidate pool in description, keeping evidence in strongClues, calibrated eliminations in contradictions, survivors in confusions, and best separator in nextThingsToInspect.', 'deep-geography': 'DEEP GEOGRAPHY: explain a grounded causal story in natural learner-facing prose: the visible feature, its function, its supported physical or human cause, the resulting landscape, and its comparison value. Never print that recipe as a label sequence. If a generic object has no defensible geographic cause, say so plainly; do not substitute generic rankings.', memory: 'MEMORY COACH: put a truthful anchor in description, cause/effect in strongClues, exceptions in weakClues, contrasts in confusions, and recall questions in nextThingsToInspect.', 'pro-analyst': 'PRO ANALYST: put calibrated verdict in description, weighted positives in strongClues, low-value evidence in weakClues, conflicts in contradictions, ambiguity in confusions, and information gain in nextThingsToInspect.' };
const depths: Record<Depth, string> = { short: 'DEPTH SHORT: 2–5 major clues, quickly readable.', normal: 'DEPTH NORMAL: major clues, confusers, short explanation, one takeaway.', deep: 'DEPTH DEEP: relevant context and multiple confusers without a wall of text.' };
const allowedOrigins = (Deno.env.get('COACH_ALLOWED_ORIGINS') || 'http://localhost:3000,https://aljohnpolyglot.github.io').split(',');
const keyStates: KeyState[] = [...new Set((Deno.env.get('GEMINI_API_KEYS') || Deno.env.get('GEMINI_API_KEY') || '').split(',').map((key) => key.trim()).filter(Boolean))].map((key) => ({ key, cooldownUntil: 0 }));
let keyCursor = keyStates.length ? Math.floor(Math.random() * keyStates.length) : 0;

const schema = { type: 'OBJECT', properties: {
  confidence: { type: 'STRING', enum: ['low', 'medium', 'high'] }, region: { type: 'STRING' }, locationEstimate: { type: 'OBJECT', properties: { level: { type: 'STRING', enum: ['region', 'city', 'exact'] }, label: { type: 'STRING' }, confidence: { type: 'STRING', enum: ['medium', 'high'] }, basis: { type: 'ARRAY', items: { type: 'STRING' } } }, required: ['level', 'label', 'confidence', 'basis'] }, regionalRead: { type: 'OBJECT', properties: { label: { type: 'STRING' }, confidence: { type: 'STRING', enum: ['low', 'medium', 'high'] }, reason: { type: 'STRING' } }, required: ['label', 'confidence', 'reason'] }, description: { type: 'STRING' },
  candidates: { type: 'ARRAY', items: { type: 'OBJECT', properties: { countryCode: { type: 'STRING' }, confidence: { type: 'NUMBER' }, rationale: { type: 'STRING' } }, required: ['countryCode', 'confidence', 'rationale'] } },
  strongClues: { type: 'ARRAY', items: { type: 'STRING' } }, weakClues: { type: 'ARRAY', items: { type: 'STRING' } }, contradictions: { type: 'ARRAY', items: { type: 'STRING' } }, confusions: { type: 'ARRAY', items: { type: 'STRING' } }, nextThingsToInspect: { type: 'ARRAY', items: { type: 'STRING' } },
  coreCard: { type: 'OBJECT', properties: { front: { type: 'ARRAY', items: { type: 'STRING' } }, backExplanation: { type: 'STRING' } }, required: ['front', 'backExplanation'] },
  extraCards: { type: 'ARRAY', items: { type: 'OBJECT', properties: { category: { type: 'STRING' }, front: { type: 'ARRAY', items: { type: 'STRING' } }, back: { type: 'STRING' }, clueStrength: { type: 'INTEGER' } }, required: ['category', 'front', 'back', 'clueStrength'] } },
}, required: ['confidence', 'region', 'description', 'candidates', 'strongClues', 'weakClues', 'contradictions', 'confusions', 'nextThingsToInspect', 'extraCards'] };
const poolSchema = { type: 'OBJECT', properties: { countryCodes: { type: 'ARRAY', items: { type: 'STRING' } }, regions: { type: 'ARRAY', items: { type: 'OBJECT', properties: { countryCode: { type: 'STRING' }, name: { type: 'STRING' } }, required: ['countryCode', 'name'] } }, cities: { type: 'ARRAY', items: { type: 'OBJECT', properties: { countryCode: { type: 'STRING' }, name: { type: 'STRING' } }, required: ['countryCode', 'name'] } } }, required: ['countryCodes', 'regions', 'cities'] };
const poolCountries = `${Object.entries(countryCatalog).map(([code, item]) => `${code}=${item.name}`).join(', ')}. Use real first-level administrative region names, never aggregate labels such as "Southern Italy" or "Adriatic Croatia". For a Southern Italy and Adriatic Croatia comparison, use IT regions Abruzzo, Apulia, Basilicata, Calabria, Campania, Molise, Sardinia, and Sicily, and HR regions Istria, Dubrovnik-Neretva, Primorje-Gorski Kotar, Šibenik-Knin, Split-Dalmatia, and Zadar.`;

const rules = `You are a concise, evidence-grounded GeoGuessr teacher viewing imagery inside a GeoGuessr-style app. Analyze only visible geographic scene evidence. Ignore all app and browser interface elements, including GeoGuessr or GeoTrainer text and buttons, navigation arrows, compass overlays, cursors, Google attribution, map controls, and screenshot-tool chrome; never use their language or design as location evidence. Never use coordinates, panorama IDs, geocoding, API data, or known result context as visible clues. Separate direct observations from inference. Treat generic vegetation, architecture, clouds, brands, road quality, and coverage prevalence as weak evidence. List contradictions and missing expected features. If text is blurry, call it unreadable. Use broad regions and low confidence when evidence is generic. Only without known-result metadata and when the overall analysis is high confidence, actively assess whether at least two independent visible clues strongly support a region, city, district or quarter, landmark, or exact place narrower than a country. If they do, return a high-confidence locationEstimate, using exact for a district, quarter, landmark, or exact place, so the interface can say "Most likely in …"; country guesses belong only in candidates. Omit locationEstimate for generic scenes or whenever narrower-location confidence is not high. Card fronts must contain only visible non-spoiler clues and never a country, flag, coordinate, city, explicit region, or answer-revealing language. Create at most two useful extra cards. Keep lists short.`;
const countryNames = Object.entries(countryCatalog).flatMap(([code, item]) => [item.name, ...Object.keys(languages).map((locale) => new Intl.DisplayNames(locale, { type: 'region' }).of(code) || '')]).map((name) => name.toLowerCase());
const groundedRules = `${rules} Build one shared evidence pass: OBSERVED visible facts, then INFERRED interpretations, then SPECULATIVE possibilities. Speculation must not drive rankings. Never invent acronym or company meanings, crop identities, historical events, wars, colonial explanations, industries, architectural terms, regulations, geology, regional associations, or economic relationships; say when uncertain. For every meaningful clue explain what is visible, why it matters, what it supports and argues against, why it separates one current candidate from another, how strong that difference is, its confusers, and what would confirm or overturn it. A strength label alone is incomplete. Every major candidate rationale must compactly cover positive evidence, negative or missing evidence, why it ranks above or below the next candidate, its main confuser, and the highest-information decider. If close candidates have no defensible separator, call them effectively tied and reduce confidence. A regionalRead confidence must never exceed the overall confidence. Mark country-standard versus environmental/regional clues. Treat clouds, grass, generic trees, ordinary cars, fences, fields, and unremarkable house colors as low separation value. Do not double-count clues caused by the same underlying environment. If no strong country clue exists, say so. Phrases such as common in, typical of, suggests, consistent with, or often found in are incomplete unless followed by the cause, comparison, limitation, and separation value. Explain why each next clue has high information gain.`;

function cors(origin: string | null) {
  const allowed = origin && allowedOrigins.includes(origin) ? origin : allowedOrigins[0];
  return { 'access-control-allow-origin': allowed, 'access-control-allow-headers': 'authorization, apikey, content-type', 'access-control-allow-methods': 'POST, OPTIONS', vary: 'Origin' };
}
function json(body: unknown, status: number, origin: string | null) { return new Response(JSON.stringify(body), { status, headers: { ...cors(origin), 'content-type': 'application/json' } }); }
const decodeText = (value: string) => value
  .replace(/\\u([0-9a-f]{4})/gi, (_, hex: string) => String.fromCharCode(Number.parseInt(hex, 16)))
  .replace(/(\p{L})(?:u)?(00[89a-f][0-9a-f])(?=$|[^\p{L}\p{N}])/giu, (_, lead: string, hex: string) => lead + String.fromCharCode(Number.parseInt(hex, 16)));
const stripScaffolds = (value: string) => decodeText(value).split(/\n+|(?<=[.!?])\s+/u).filter((part) => (part.match(/→|->/g) || []).length < 3).join(' ').trim();
function strings(value: unknown, max = 6) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string').map((item) => decodeText(item).trim()).filter(Boolean).slice(0, max) : []; }
function context(value: unknown) {
  if (!value || typeof value !== 'object') return undefined;
  const source = value as Record<string, unknown>; const text = (key: string) => typeof source[key] === 'string' ? String(source[key]).slice(0, 120) : undefined; const number = (key: string) => Number.isFinite(source[key]) ? Number(source[key]) : undefined;
  return { actualCountry: text('actualCountry'), actualRegion: text('actualRegion'), guessedCountry: text('guessedCountry'), score: number('score'), distanceKm: number('distanceKm'), previousAttempts: Array.isArray(source.previousAttempts) ? source.previousAttempts.slice(0, 5) : undefined, previousCoachCandidates: Array.isArray(source.previousCoachCandidates) ? source.previousCoachCandidates.filter((item): item is string => typeof item === 'string').slice(0, 4) : undefined };
}
function knowledge(countryName = '') {
  const key = (value: string) => value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').replace(/^the\s+/, '').trim();
  const country = (hintsData.countries as Array<{ name: string; hints?: Array<{ cat?: string; type?: string; text?: string; uniq?: string }> }>).find((item) => key(item.name) === key(countryName));
  return (country?.hints || []).sort((a, b) => Number(b.uniq === 'unique') - Number(a.uniq === 'unique')).filter((hint) => hint.text).slice(0, 6).map((hint) => ({ category: hint.cat || 'country', type: hint.type || 'general', text: hint.text!.replace(/\*\*/g, '').slice(0, 500) }));
}
function metaKnowledge(countryName = '') {
  const key = (value: string) => value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').replace(/^the\s+/, '').trim();
  const country = (geometasData.countries as Array<{ name: string; hints?: Array<{ tags?: string[]; text?: string }> }>).find((item) => key(item.name) === key(countryName)); const hints = country?.hints || []; const diverse = [...new Map(hints.map((hint) => [hint.tags?.[0] || 'general', hint])).values(), ...hints];
  return [...new Set(diverse)].slice(0, 8).flatMap((hint) => typeof hint.text === 'string' ? [{ type: hint.tags?.join(', ') || 'general', text: hint.text.slice(0, 700), source: 'https://geometas.com/' }] : []);
}
function instruction(mode: Mode, language: string, known?: Record<string, unknown>, style: Style = 'quick', depth: Depth = 'normal') {
  const lead = `MANDATORY OUTPUT LANGUAGE: ${languages[language] || 'English'}. Write every natural-language JSON string value only in that language, even when signs or reference facts use another language. Never translate JSON property names, ISO country codes, or card category identifiers. Never echo prompt instructions, field names, style recipes, evidence-category scaffolds, or sequences such as WHAT → FUNCTION → CAUSE; write only polished learner-facing content inside each field. Return every candidate countryCode as an uppercase ISO 3166-1 alpha-2 code and confidence as a relative AI estimate from 0 to 1, not a measured probability. Every rationale must follow the shared comparative rules. The top candidate must include strongest clues, main confuser, separator, and highest-information next clue. Return regionalRead only when supported; otherwise explain why regional identification is impossible in contradictions. ${styles[style]} ${depths[depth]} `;
  if (mode === 'hints') return lead + 'Give only spoiler-free things to inspect in nextThingsToInspect. Name no country, city, region, coordinate, or likely answer; leave all other fields empty.';
  if (mode === 'analyze360') return lead + 'Synthesize four views 90 degrees apart. Rank up to four candidates with honest confidence. For every candidate, rationale must explain in one specific sentence which visible evidence supports that country and what distinguishes it from the others. Separate strong, weak, contradictory, and missing evidence without counting repeated features twice. Add locationEstimate only when its strict visible-evidence threshold is met. Leave cards empty.';
  if (mode === 'clue-safe') return lead + 'Treat this as a user-selected clue crop. Identify the intended foreground object at the narrowest visually defensible level. For a sign, explain the visible symbol, letter, number, color, and restriction or instruction it communicates; do not stop at its shape. For a readable brand or organization, explain what it is and the clue reliability, including whether its products or presence can cross borders. For vegetation, attempt a plant family or species and cite visible identifying traits. For road furniture, name the feature type and its exact colors, shape, reflector, stripe, border, and mounting pattern. If resolution is insufficient, say the exact identity is unreadable and name the detail needed; never invent specificity. Use surrounding context only as supporting or contradictory evidence. Describe useful traits, limitations, and comparison features. Name or infer no location; leave region, candidates, confusions, and cards empty.';
  if (mode === 'clue') return lead + 'Treat this as a user-selected clue crop. Identify the intended foreground object at the narrowest visually defensible level. For a sign, explain the visible symbol, letter, number, color, and restriction or instruction it communicates; do not stop at its shape or possible countries. For a readable brand or organization, explain what it is, where it originates or primarily operates, and whether its products or presence cross borders so the evidence strength makes sense. For vegetation, attempt a plant family or species and cite visible identifying traits. For road furniture, name the feature type and its exact colors, shape, reflector, stripe, border, and mounting pattern. If resolution is insufficient, say the exact identity is unreadable and name the detail needed; never invent specificity. Use surrounding context only as supporting or contradictory evidence. Explain where that specific variant is commonly found, where it also occurs, and how reliable it is; do not turn a broad plant range into country-level confidence. Give a broad region and up to four candidates. For every candidate, rationale must explain in one specific sentence which visible evidence supports that country and what distinguishes it from the others. Include realistic confusions, limitations, contradictions, and comparison features. Add locationEstimate only when its strict visible-evidence threshold is met. Leave cards empty.';
  if (mode === 'analyze') return lead + 'Give a short region or vibe and up to four candidate countries. For every candidate, rationale must explain in one specific sentence which visible evidence supports that country and what distinguishes it from the others. Include direct strong clues, generic weak clues, contradictions, and what to inspect next. Add locationEstimate only when its strict visible-evidence threshold is met. Leave cards empty.';
  const reference = known ? knowledge(String(known.actualCountry || '')) : [];
  const metas = mode === 'explain' ? metaKnowledge(String(known?.actualCountry || '')) : [];
  const metaReference = mode === 'explain' ? ` GeoMetas facts for only that country: ${JSON.stringify(metas)}. Mention a reference fact only when its described feature is clearly visible in the supplied image; otherwise ignore it completely.` : '';
  return lead + `Known result context is an answer key only: ${JSON.stringify(known || {})}. Reference facts for only that country: ${JSON.stringify(reference)}.${metaReference} ` + (mode === 'cards' ? 'Create one core card plus only genuinely useful specialized cards from visible clues.' : 'Explain which visible clues fit, which are generic, and realistic confusions. If the image alone was insufficient, say so plainly. If previous Coach candidates missed the answer, acknowledge why; never retrofit generic clues as proof. Leave region, locationEstimate, and candidates empty.');
}
function normalize(value: unknown, mode: Mode, actualCountry = '') {
  if (!value || typeof value !== 'object') throw new Error('Coach returned malformed JSON.');
  const item = value as Record<string, unknown>; const banned = [actualCountry.toLowerCase(), ...countryNames].filter(Boolean); const nonVisual = /\b(?:location\s+metadata|coordinates?|latitude|longitude|pano(?:rama)?\s*(?:id)?|geocod(?:e|ing)|api)\b|[-+]?\d{1,2}\.\d{3,}\s*[°º]?\s*[NS]?\s*[,/]\s*[-+]?\d{1,3}\.\d{3,}/iu; const visible = (line: string) => !nonVisual.test(line); const safe = (line: string) => visible(line) && !banned.some((name) => name.length > 2 && line.toLowerCase().includes(name));
  const candidateMap = new Map<string, { confidence: number; rationale?: string }>(); if (Array.isArray(item.candidates)) item.candidates.forEach((raw) => { if (!raw || typeof raw !== 'object') return; const entry = raw as Record<string, unknown>; const code = String(entry.countryCode || '').toUpperCase(); const confidence = Math.min(1, Math.max(0, Number(entry.confidence))); const previous = candidateMap.get(code); if (countryCatalog[code] && Number.isFinite(entry.confidence) && (!previous || confidence >= previous.confidence)) candidateMap.set(code, { confidence, ...(typeof entry.rationale === 'string' ? { rationale: decodeText(entry.rationale).trim().slice(0, 900) } : {}) }); });
  const candidates = [...candidateMap].map(([countryCode, candidate]) => ({ countryCode, ...candidate, ...(candidate.rationale ? { rationale: candidate.rationale.slice(0, 900) } : {}) })).sort((a, b) => b.confidence - a.confidence).slice(0, 4); const total = candidates.reduce((sum, entry) => sum + entry.confidence, 0); if (total > 1) candidates.forEach((entry) => { entry.confidence /= total; }); const requestedConfidence = ['low', 'medium', 'high'].includes(String(item.confidence)) ? String(item.confidence) : 'low'; const confidence = !candidates.length ? 'low' : requestedConfidence === 'high' && candidates[0].confidence < .65 ? 'medium' : requestedConfidence === 'medium' && candidates[0].confidence < .2 ? 'low' : requestedConfidence;
  const rawEstimate = item.locationEstimate && typeof item.locationEstimate === 'object' ? item.locationEstimate as Record<string, unknown> : undefined; const estimateLevel = String(rawEstimate?.level); const estimateConfidence = String(rawEstimate?.confidence); const estimateBasis = strings(rawEstimate?.basis, 4).filter(visible); const estimateLabel = typeof rawEstimate?.label === 'string' ? decodeText(rawEstimate.label).trim().slice(0, 160) : ''; const locationEstimate = confidence === 'high' && !actualCountry && ['analyze', 'analyze360', 'clue'].includes(mode) && ['region', 'city', 'exact'].includes(estimateLevel) && estimateConfidence === 'high' && estimateLabel && !countryNames.includes(estimateLabel.toLowerCase()) && visible(estimateLabel) && estimateBasis.length >= 2 ? { level: estimateLevel, label: estimateLabel, confidence: estimateConfidence, basis: estimateBasis } : undefined;
  const rawRegional = item.regionalRead && typeof item.regionalRead === 'object' ? item.regionalRead as Record<string, unknown> : undefined; const regionalConfidence = ['low', 'medium', 'high'].includes(String(rawRegional?.confidence)) ? String(rawRegional?.confidence) as 'low' | 'medium' | 'high' : undefined; const confidenceRank = { low: 0, medium: 1, high: 2 }; const regionalRead = !actualCountry && regionalConfidence && typeof rawRegional?.label === 'string' && typeof rawRegional.reason === 'string' && visible(rawRegional.label) && visible(rawRegional.reason) ? { label: decodeText(rawRegional.label).slice(0, 120), confidence: confidenceRank[regionalConfidence] > confidenceRank[confidence as 'low' | 'medium' | 'high'] ? confidence : regionalConfidence, reason: decodeText(rawRegional.reason).slice(0, 500) } : undefined;
  const core = item.coreCard && typeof item.coreCard === 'object' ? item.coreCard as Record<string, unknown> : undefined; const result = { confidence, region: typeof item.region === 'string' ? decodeText(item.region).slice(0, 120) : '', locationEstimate, description: typeof item.description === 'string' ? stripScaffolds(item.description).slice(0, 1200) || undefined : undefined, candidates, strongClues: strings(item.strongClues).filter(visible), weakClues: strings(item.weakClues).filter(visible), contradictions: strings(item.contradictions).filter(visible), confusions: strings(item.confusions), nextThingsToInspect: strings(item.nextThingsToInspect).filter(visible), coreCard: mode === 'cards' && core ? { front: strings(core.front).filter(safe), backExplanation: typeof core.backExplanation === 'string' ? decodeText(core.backExplanation).slice(0, 900) : '' } : undefined, extraCards: [] as unknown[] };
  Object.assign(result, { regionalRead: ['hints', 'clue-safe', 'explain'].includes(mode) ? undefined : regionalRead });
  result.extraCards = mode === 'cards' && Array.isArray(item.extraCards) ? item.extraCards.flatMap((raw) => { if (!raw || typeof raw !== 'object') return []; const card = raw as Record<string, unknown>; const front = strings(card.front, 5).filter(safe); return front.length && typeof card.back === 'string' ? [{ category: String(card.category || 'Roads'), front, back: decodeText(card.back).slice(0, 700), clueStrength: Math.max(1, Math.min(5, Number(card.clueStrength) || 1)) }] : []; }).slice(0, 2) : [];
  if (mode === 'hints') return { ...result, region: '', candidates: [], strongClues: [], weakClues: [], contradictions: [], confusions: [], nextThingsToInspect: result.nextThingsToInspect.filter(safe), coreCard: undefined, extraCards: [] };
  if (mode === 'clue-safe') return { ...result, region: '', description: result.description && safe(result.description) ? result.description : undefined, candidates: [], strongClues: result.strongClues.filter(safe), weakClues: result.weakClues.filter(safe), contradictions: result.contradictions.filter(safe), confusions: [], nextThingsToInspect: result.nextThingsToInspect.filter(safe), coreCard: undefined, extraCards: [] };
  if (mode === 'clue') return { ...result, coreCard: undefined, extraCards: [] }; if (mode === 'explain') return { ...result, region: '', locationEstimate: undefined, candidates: [] }; return result;
}
const englishLeakWords = new Set(['the', 'and', 'this', 'that', 'with', 'from', 'which', 'where', 'other', 'look', 'likely', 'common', 'road', 'sign', 'country', 'overall', 'suggests', 'found', 'appears', 'nearby', 'buildings', 'vehicles', 'lighting', 'daytime', 'background', 'check', 'style', 'used', 'green', 'yellow']);
function languageMatches(analysis: ReturnType<typeof normalize>, language: string) {
  if (language === 'en') return true;
  const text = [analysis.region, analysis.description, analysis.regionalRead?.label, analysis.regionalRead?.reason, ...analysis.candidates.flatMap((item) => item.rationale || []), ...analysis.strongClues, ...analysis.weakClues, ...analysis.contradictions, ...analysis.confusions, ...analysis.nextThingsToInspect].filter(Boolean).join(' ').toLowerCase(); const words = text.match(/[a-zÀ-ž]+/gu) || []; const english = words.filter((word) => englishLeakWords.has(word)).length;
  return english < 8 || english / Math.max(words.length, 1) < .12;
}
const vagueRationale = [/consistent with|similar to|common in|typical of/iu, /coerente con|simile (?:a|agli?|alle?)|comune in|tipic[oa]/iu, /coherente con|similar a|común en|típic[oa]/iu, /coerente com|semelhante a|comum em|típic[oa]/iu, /cohérent avec|similaire à|courant en|typique de/iu, /entspricht|ähnlich(?:e|er|es)?|typisch für/iu, /характерн\w* для|похож\w* на|типичн\w* для/iu, /stämmer överens med|liknar|typisk(?:t)? för/iu];
const rationalesAreSpecific = (analysis: ReturnType<typeof normalize>) => analysis.candidates.every((candidate) => !!candidate.rationale && (candidate.rationale.length >= 180 || !vagueRationale.some((pattern) => pattern.test(candidate.rationale!))));
function base64(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); let binary = ''; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }
async function streetView(view: unknown, headingOffset = 0): Promise<Frame> {
  const key = Deno.env.get('GOOGLE_MAPS_API_KEY') || ''; if (!key) throw new Error('Street View server key is not configured.'); if (!view || typeof view !== 'object') throw new Error('Current Street View orientation is unavailable.'); const item = view as Record<string, unknown>; const pano = String(item.panoId || ''); const heading = Number(item.heading); const pitch = Number(item.pitch); const zoom = Number(item.zoom); if (!pano || ![heading, pitch, zoom].every(Number.isFinite)) throw new Error('Current Street View orientation is invalid.');
  const query = new URLSearchParams({ size: '640x480', pano, heading: String((heading + headingOffset + 360) % 360), pitch: String(Math.max(-90, Math.min(90, pitch))), fov: String(Math.max(25, Math.min(100, 180 / 2 ** zoom))), key }); const response = await fetch(`https://maps.googleapis.com/maps/api/streetview?${query}`, { signal: AbortSignal.timeout(8_000) }); if (!response.ok) throw new Error(`Street View capture failed (${response.status}).`); const mimeType = response.headers.get('content-type')?.split(';')[0] || ''; if (!mimeType.startsWith('image/')) throw new Error('Street View capture returned no image.'); return { mimeType, imageData: base64(await response.arrayBuffer()) };
}
async function gemini(mode: Mode, frames: Frame[], known: Record<string, unknown> | undefined, language: string, style: Style, depth: Depth) {
  if (!keyStates.length) throw new Error('Gemini keys are not configured.');
  const models = (Deno.env.get('GEMINI_COACH_MODELS') || 'gemini-2.5-flash-lite,gemini-2.5-flash').split(','); let last = new Error('Gemini Coach is unavailable.'); let groundedFallback: { analysis: ReturnType<typeof normalize>; model: string; generatedAt: number } | undefined;
  for (const model of models) for (let attempt = 0; attempt < keyStates.length; attempt++) {
    const state = keyStates[keyCursor++ % keyStates.length]; if (state.cooldownUntil > Date.now()) continue;
    try {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model.trim())}:generateContent`, { method: 'POST', signal: AbortSignal.timeout(mode === 'analyze360' ? 35_000 : 25_000), headers: { 'content-type': 'application/json', 'x-goog-api-key': state.key }, body: JSON.stringify({ systemInstruction: { parts: [{ text: groundedRules }] }, contents: [{ role: 'user', parts: [{ text: instruction(mode, language, known, style, depth) }, ...frames.map((frame) => ({ inlineData: { mimeType: frame.mimeType, data: frame.imageData } }))] }], generationConfig: { temperature: .25, maxOutputTokens: depth === 'deep' ? 3400 : depth === 'short' ? 1600 : 2400, thinkingConfig: { thinkingBudget: 0 }, responseMimeType: 'application/json', responseSchema: schema } }) });
      if (response.status === 429) { state.cooldownUntil = Date.now() + 60_000; last = new Error('Gemini quota exceeded.'); continue; }
      if (!response.ok) { const failure = await response.clone().json().catch(() => undefined) as { error?: { status?: string; message?: string; details?: Array<{ reason?: string }> } } | undefined; const leaked = /reported as leaked/i.test(failure?.error?.message || ''); const reason = failure?.error?.details?.find((detail) => detail.reason)?.reason || failure?.error?.status; last = new Error(response.status >= 500 ? 'Gemini service error.' : leaked ? 'Gemini API key was disabled by Google. Update the server key and try again.' : `Gemini request was rejected (${response.status}${reason ? `: ${reason}` : ''}).`); continue; }
      const raw = await response.json(); const text = raw.candidates?.[0]?.content?.parts?.find((part: { text?: string }) => part.text)?.text; if (!text) throw new Error('Gemini returned an empty response.');
      const analysis = normalize(JSON.parse(text), mode, String(known?.actualCountry || '')); if (!languageMatches(analysis, language)) { last = new Error('Gemini returned mixed-language output.'); continue; } if (['analyze', 'analyze360', 'clue'].includes(mode) && !rationalesAreSpecific(analysis)) { groundedFallback ||= { analysis, model: model.trim(), generatedAt: Date.now() }; last = new Error('Gemini returned vague candidate reasoning.'); continue; }
      return { analysis, model: model.trim(), generatedAt: Date.now() };
    } catch (error) { last = error instanceof Error && error.name === 'TimeoutError' ? new Error('Gemini request timed out.') : error as Error; }
  }
  if (groundedFallback) return groundedFallback;
  throw last;
}
function normalizePool(value: unknown) {
  if (!value || typeof value !== 'object') throw new Error('Gemini returned malformed JSON.'); const source = value as Record<string, unknown>;
  const places = (key: 'regions' | 'cities') => Array.isArray(source[key]) ? source[key].flatMap((value) => { const item = value && typeof value === 'object' ? value as Record<string, unknown> : {}; const countryCode = String(item.countryCode || '').toUpperCase(); const name = String(item.name || '').trim().slice(0, 120); return countryCode in countryCatalog && name ? [{ countryCode, name }] : []; }).slice(0, 80) : [];
  const regions = places('regions'), cities = places('cities'); const countryCodes = [...new Set([...(Array.isArray(source.countryCodes) ? source.countryCodes.map(String).map((code) => code.toUpperCase()).filter((code) => code in countryCatalog) : []), ...regions.map((place) => place.countryCode), ...cities.map((place) => place.countryCode)])].slice(0, 40);
  if (!countryCodes.length) throw new Error('Gemini returned no valid countries.'); return { countryCodes, regions, cities };
}
async function poolGemini(description: string) {
  if (!keyStates.length) throw new Error('Gemini keys are not configured.'); const models = (Deno.env.get('GEMINI_POOL_MODELS') || 'gemini-2.5-flash').split(','); let last = new Error('Gemini Coach is unavailable.');
  for (const model of models) for (let attempt = 0; attempt < keyStates.length; attempt++) { const state = keyStates[keyCursor++ % keyStates.length]; if (state.cooldownUntil > Date.now()) continue; try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model.trim())}:generateContent`, { method: 'POST', signal: AbortSignal.timeout(25_000), headers: { 'content-type': 'application/json', 'x-goog-api-key': state.key }, body: JSON.stringify({ contents: [{ role: 'user', parts: [{ text: `Turn this learning request, written in any language, into a precise GeoTrainer pool: ${JSON.stringify(description)}. Preserve every explicitly named place unless excluded. Understand contextual abbreviations (for example, SA means South Africa in an Australia–SA–Argentina desert comparison). A request for lookalikes, common confusers, or a shared landscape is a comparison set, not a request to choose just one place. Include only countries or territories satisfying every geographic, language, island or coastal, inclusion, and exclusion constraint. Geography overrides a shared language: Equatorial Guinea is not Latin America. Treat words such as only, excluding, islands, countries, coast, and language as strict filters. Do not add a parent country for a territory that has its own allowed code. Do not broaden to nearby, culturally related, or same-language places unless the learner explicitly asks for suggested confusers. When a landscape or coastal theme applies only to part of a country, return matching regions so the whole country is not sampled; use cities only for an explicitly urban request. Examples: "Spanish-speaking Caribbean islands" means CU, DO, and PR, not Spain, the US, or mainland Latin America; "Mediterranean island countries" means CY and MT, not countries that merely contain islands; "deutschsprachige Alpenländer, aber nicht Deutschland" excludes DE; "Australia, SA, Argentina deserts" preserves AU, ZA, and AR and narrows each to dry regions. Otherwise leave region and city arrays empty. Do not invent places. Use this allowed ISO list: ${poolCountries}` }] }], generationConfig: { temperature: 0, maxOutputTokens: 1800, thinkingConfig: { thinkingBudget: 0 }, responseMimeType: 'application/json', responseSchema: poolSchema } }) });
    if (response.status === 429) { state.cooldownUntil = Date.now() + 60_000; last = new Error('Gemini quota exceeded.'); continue; } if (!response.ok) { last = new Error(response.status >= 500 ? 'Gemini service error.' : `Gemini request was rejected (${response.status}).`); continue; }
    const raw = await response.json(); const text = raw.candidates?.[0]?.content?.parts?.find((part: { text?: string }) => part.text)?.text; if (!text) throw new Error('Gemini returned an empty response.'); return normalizePool(JSON.parse(text));
  } catch (error) { last = error instanceof Error && (error.name === 'TimeoutError' || error.name === 'AbortError') ? new Error('Gemini request timed out.') : error as Error; } }
  throw last;
}

Deno.serve(async (request) => {
  const origin = request.headers.get('origin'); if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: cors(origin) }); if (request.method !== 'POST') return json({ error: 'Method not allowed.' }, 405, origin);
  try {
    const value = await request.json() as Record<string, unknown>; if (JSON.stringify(value).length > 12_000_000) throw new Error('Screenshot is too large.');
    if (value.mode === 'capture') { const frame = await streetView(value.view); return json({ imageDataUrl: `data:${frame.mimeType};base64,${frame.imageData}` }, 200, origin); }
    if (value.mode === 'pool') { const description = typeof value.description === 'string' ? value.description.trim().slice(0, 500) : ''; if (description.length < 3) throw new Error('Describe what you want to learn.'); return json({ pool: await poolGemini(description) }, 200, origin); }
    const mode = value.mode as Mode; if (!modes.has(mode)) throw new Error('Invalid Coach request.');
    const supplied = ['image/jpeg', 'image/png', 'image/webp'].includes(String(value.mimeType)) && /^[A-Za-z0-9+/=]+$/.test(String(value.imageData || ''));
    const frames = supplied ? [{ mimeType: String(value.mimeType), imageData: String(value.imageData) }] : mode === 'analyze360' ? await Promise.all([0, 90, 180, 270].map((offset) => streetView(value.view, offset))) : [await streetView(value.view)];
    const language = Object.hasOwn(languages, String(value.language)) ? String(value.language) : 'en'; const style = Object.hasOwn(styles, String(value.style)) ? value.style as Style : 'quick'; const depth = Object.hasOwn(depths, String(value.depth)) ? value.depth as Depth : 'normal';
    const known = ['hints', 'analyze', 'clue', 'clue-safe'].includes(mode) ? undefined : context(value.context); return json(await gemini(mode, frames, known, language, style, depth), 200, origin);
  } catch (error) { const message = error instanceof Error ? error.message : 'Coach unavailable.'; return json({ error: message }, /timed out/i.test(message) ? 504 : /quota|cooling/i.test(message) ? 429 : 503, origin); }
});
