import countryCatalog from '../../../src/data/countryCatalog.json' with { type: 'json' };
import hintsData from '../../../server/data/geoguessr-hints.json' with { type: 'json' };
import geometasData from '../../../server/data/geometas-hints.json' with { type: 'json' };

type Mode = 'hints' | 'analyze' | 'analyze360' | 'explain' | 'cards' | 'clue' | 'clue-safe';
type Frame = { mimeType: string; imageData: string };
type KeyState = { key: string; cooldownUntil: number };
const modes = new Set<Mode>(['hints', 'analyze', 'analyze360', 'explain', 'cards', 'clue', 'clue-safe']);
const languages: Record<string, string> = { en: 'English', es: 'Spanish', pt: 'Portuguese', fr: 'French', de: 'German', it: 'Italian', ru: 'Russian', sv: 'Swedish' };
const allowedOrigins = (Deno.env.get('COACH_ALLOWED_ORIGINS') || 'http://localhost:3000,https://aljohnpolyglot.github.io').split(',');
const keyStates: KeyState[] = (Deno.env.get('GEMINI_API_KEYS') || Deno.env.get('GEMINI_API_KEY') || '').split(',').map((key) => key.trim()).filter(Boolean).map((key) => ({ key, cooldownUntil: 0 }));
let keyCursor = 0;

const schema = { type: 'OBJECT', properties: {
  confidence: { type: 'STRING', enum: ['low', 'medium', 'high'] }, region: { type: 'STRING' }, locationEstimate: { type: 'OBJECT', properties: { level: { type: 'STRING', enum: ['region', 'city', 'exact'] }, label: { type: 'STRING' }, confidence: { type: 'STRING', enum: ['medium', 'high'] }, basis: { type: 'ARRAY', items: { type: 'STRING' } } }, required: ['level', 'label', 'confidence', 'basis'] }, description: { type: 'STRING' },
  candidates: { type: 'ARRAY', items: { type: 'OBJECT', properties: { countryCode: { type: 'STRING' }, confidence: { type: 'NUMBER' } }, required: ['countryCode', 'confidence'] } },
  strongClues: { type: 'ARRAY', items: { type: 'STRING' } }, weakClues: { type: 'ARRAY', items: { type: 'STRING' } }, contradictions: { type: 'ARRAY', items: { type: 'STRING' } }, confusions: { type: 'ARRAY', items: { type: 'STRING' } }, nextThingsToInspect: { type: 'ARRAY', items: { type: 'STRING' } },
  coreCard: { type: 'OBJECT', properties: { front: { type: 'ARRAY', items: { type: 'STRING' } }, backExplanation: { type: 'STRING' } }, required: ['front', 'backExplanation'] },
  extraCards: { type: 'ARRAY', items: { type: 'OBJECT', properties: { category: { type: 'STRING' }, front: { type: 'ARRAY', items: { type: 'STRING' } }, back: { type: 'STRING' }, clueStrength: { type: 'INTEGER' } }, required: ['category', 'front', 'back', 'clueStrength'] } },
}, required: ['confidence', 'region', 'candidates', 'strongClues', 'weakClues', 'contradictions', 'confusions', 'nextThingsToInspect', 'extraCards'] };

const rules = `You are a concise, evidence-grounded GeoGuessr teacher. Analyze only visible evidence. Never use coordinates, panorama IDs, geocoding, API data, or known result context as visible clues. Separate direct observations from inference. Treat generic vegetation, architecture, clouds, brands, road quality, and coverage prevalence as weak evidence. List contradictions and missing expected features. If text is blurry, call it unreadable. Use broad regions and low confidence when evidence is generic. Only without known-result metadata, locationEstimate may name a region, city, landmark, or exact place when at least two independent visible clues strongly support it; city and exact estimates require high confidence plus readable or uniquely identifying evidence. Otherwise omit it. Card fronts must contain only visible non-spoiler clues and never a country, flag, coordinate, city, explicit region, or answer-revealing language. Create at most two useful extra cards. Keep lists short.`;

function cors(origin: string | null) {
  const allowed = origin && allowedOrigins.includes(origin) ? origin : allowedOrigins[0];
  return { 'access-control-allow-origin': allowed, 'access-control-allow-headers': 'authorization, apikey, content-type', 'access-control-allow-methods': 'POST, OPTIONS', vary: 'Origin' };
}
function json(body: unknown, status: number, origin: string | null) { return new Response(JSON.stringify(body), { status, headers: { ...cors(origin), 'content-type': 'application/json' } }); }
const decodeText = (value: string) => value.replace(/\\u([0-9a-f]{4})/gi, (_, hex: string) => String.fromCharCode(Number.parseInt(hex, 16)));
function strings(value: unknown, max = 6) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string').map((item) => decodeText(item).trim()).filter(Boolean).slice(0, max) : []; }
function context(value: unknown) {
  if (!value || typeof value !== 'object') return undefined;
  const source = value as Record<string, unknown>; const text = (key: string) => typeof source[key] === 'string' ? String(source[key]).slice(0, 120) : undefined; const number = (key: string) => Number.isFinite(source[key]) ? Number(source[key]) : undefined;
  return { actualCountry: text('actualCountry'), actualRegion: text('actualRegion'), guessedCountry: text('guessedCountry'), score: number('score'), distanceKm: number('distanceKm'), previousAttempts: Array.isArray(source.previousAttempts) ? source.previousAttempts.slice(0, 5) : undefined, previousCoachCandidates: Array.isArray(source.previousCoachCandidates) ? source.previousCoachCandidates.filter((item): item is string => typeof item === 'string').slice(0, 4) : undefined };
}
function knowledge(countryName = '') {
  const key = (value: string) => value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').replace(/^the\s+/, '').trim();
  const country = (hintsData.countries as Array<{ name: string; hints?: Array<{ cat?: string; type?: string; text?: string; uniq?: string }> }>).find((item) => key(item.name) === key(countryName));
  return (country?.hints || []).sort((a, b) => Number(b.uniq === 'unique') - Number(a.uniq === 'unique')).filter((hint) => hint.text).slice(0, 6).map((hint) => ({ category: hint.cat || 'country', type: hint.type || 'general', text: hint.text!.replace(/\*\*/g, '').slice(0, 500) }));
}
function metaKnowledge(countryName = '') {
  const key = (value: string) => value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').replace(/^the\s+/, '').trim();
  const country = (geometasData.countries as Array<{ name: string; hints?: Array<{ tags?: string[]; text?: string }> }>).find((item) => key(item.name) === key(countryName)); const hints = country?.hints || []; const diverse = [...new Map(hints.map((hint) => [hint.tags?.[0] || 'general', hint])).values(), ...hints];
  return [...new Set(diverse)].slice(0, 8).flatMap((hint) => typeof hint.text === 'string' ? [{ type: hint.tags?.join(', ') || 'general', text: hint.text.slice(0, 700), source: 'https://geometas.com/' }] : []);
}
function instruction(mode: Mode, language: string, known?: Record<string, unknown>) {
  const lead = `Write all explanatory text in ${languages[language] || 'English'}. Return every candidate countryCode as an uppercase ISO 3166-1 alpha-2 code and confidence as a probability from 0 to 1. Keep card categories unchanged. `;
  if (mode === 'hints') return lead + 'Give only spoiler-free things to inspect in nextThingsToInspect. Name no country, city, region, coordinate, or likely answer; leave all other fields empty.';
  if (mode === 'analyze360') return lead + 'Synthesize four views 90 degrees apart. Rank up to four candidates with honest confidence; separate strong, weak, contradictory, and missing evidence without counting repeated features twice. Add locationEstimate only when its strict visible-evidence threshold is met.';
  if (mode === 'clue-safe') return lead + 'Treat this as a user-selected clue crop. If one foreground object is clearly intended, identify and describe it first; do not mistake unreadable details for another object. Use surrounding context only as supporting or contradictory evidence. Describe useful traits, limitations, and comparison features. Name or infer no location; leave region, candidates, confusions, and cards empty.';
  if (mode === 'clue') return lead + 'Treat this as a user-selected clue crop. If one foreground object is clearly intended, identify and describe it first; do not mistake unreadable details for another object. Use surrounding context only as supporting or contradictory evidence. Explain its geographic value, broad region, up to four candidates, realistic confusions, limitations, contradictions, and comparison features. Add locationEstimate only when its strict visible-evidence threshold is met. Leave cards empty.';
  if (mode === 'analyze') return lead + 'Give a short region or vibe, up to four candidate countries, direct strong clues, generic weak clues, contradictions, and what to inspect next. Add locationEstimate only when its strict visible-evidence threshold is met.';
  const reference = known ? knowledge(String(known.actualCountry || '')) : [];
  const metas = mode === 'explain' ? metaKnowledge(String(known?.actualCountry || '')) : [];
  const metaReference = mode === 'explain' ? ` GeoMetas facts for only that country: ${JSON.stringify(metas)}. Mention a reference fact only when its described feature is clearly visible in the supplied image; otherwise ignore it completely.` : '';
  return lead + `Known result context is an answer key only: ${JSON.stringify(known || {})}. Reference facts for only that country: ${JSON.stringify(reference)}.${metaReference} ` + (mode === 'cards' ? 'Create one core card plus only genuinely useful specialized cards from visible clues.' : 'Explain which visible clues fit, which are generic, and realistic confusions. If the image alone was insufficient, say so plainly. If previous Coach candidates missed the answer, acknowledge why; never retrofit generic clues as proof. Leave region, locationEstimate, and candidates empty.');
}
function normalize(value: unknown, mode: Mode, actualCountry = '') {
  if (!value || typeof value !== 'object') throw new Error('Coach returned malformed JSON.');
  const item = value as Record<string, unknown>; const names = Object.values(countryCatalog).map((entry) => entry.name.toLowerCase()); const banned = [actualCountry.toLowerCase(), ...names].filter(Boolean); const nonVisual = /\b(?:location\s+metadata|coordinates?|latitude|longitude|pano(?:rama)?\s*(?:id)?|geocod(?:e|ing)|api)\b|[-+]?\d{1,2}\.\d{3,}\s*[°º]?\s*[NS]?\s*[,/]\s*[-+]?\d{1,3}\.\d{3,}/iu; const visible = (line: string) => !nonVisual.test(line); const safe = (line: string) => visible(line) && !banned.some((name) => name.length > 2 && line.toLowerCase().includes(name));
  const candidateMap = new Map<string, number>(); if (Array.isArray(item.candidates)) item.candidates.forEach((raw) => { if (!raw || typeof raw !== 'object') return; const entry = raw as Record<string, unknown>; const code = String(entry.countryCode || '').toUpperCase(); if (countryCatalog[code] && Number.isFinite(entry.confidence)) candidateMap.set(code, Math.max(candidateMap.get(code) || 0, Math.min(1, Math.max(0, Number(entry.confidence))))); });
  const candidates = [...candidateMap].map(([countryCode, confidence]) => ({ countryCode, confidence })).sort((a, b) => b.confidence - a.confidence).slice(0, 4); const total = candidates.reduce((sum, entry) => sum + entry.confidence, 0); if (total > 1) candidates.forEach((entry) => { entry.confidence /= total; });
  const rawEstimate = item.locationEstimate && typeof item.locationEstimate === 'object' ? item.locationEstimate as Record<string, unknown> : undefined; const estimateLevel = String(rawEstimate?.level); const estimateConfidence = String(rawEstimate?.confidence); const estimateBasis = strings(rawEstimate?.basis, 4).filter(visible); const estimateLabel = typeof rawEstimate?.label === 'string' ? decodeText(rawEstimate.label).trim().slice(0, 160) : ''; const locationEstimate = !actualCountry && ['analyze', 'analyze360', 'clue'].includes(mode) && ['region', 'city', 'exact'].includes(estimateLevel) && ['medium', 'high'].includes(estimateConfidence) && estimateLabel && visible(estimateLabel) && estimateBasis.length >= 2 && (estimateLevel === 'region' || estimateConfidence === 'high') ? { level: estimateLevel, label: estimateLabel, confidence: estimateConfidence, basis: estimateBasis } : undefined;
  const core = item.coreCard && typeof item.coreCard === 'object' ? item.coreCard as Record<string, unknown> : undefined; const result = { confidence: ['low', 'medium', 'high'].includes(String(item.confidence)) ? item.confidence : 'low', region: typeof item.region === 'string' ? decodeText(item.region).slice(0, 120) : '', locationEstimate, description: typeof item.description === 'string' ? decodeText(item.description).slice(0, 1200) : undefined, candidates, strongClues: strings(item.strongClues).filter(visible), weakClues: strings(item.weakClues).filter(visible), contradictions: strings(item.contradictions).filter(visible), confusions: strings(item.confusions), nextThingsToInspect: strings(item.nextThingsToInspect).filter(visible), coreCard: core ? { front: strings(core.front).filter(safe), backExplanation: typeof core.backExplanation === 'string' ? decodeText(core.backExplanation).slice(0, 900) : '' } : undefined, extraCards: [] as unknown[] };
  result.extraCards = Array.isArray(item.extraCards) ? item.extraCards.flatMap((raw) => { if (!raw || typeof raw !== 'object') return []; const card = raw as Record<string, unknown>; const front = strings(card.front, 5).filter(safe); return front.length && typeof card.back === 'string' ? [{ category: String(card.category || 'Roads'), front, back: decodeText(card.back).slice(0, 700), clueStrength: Math.max(1, Math.min(5, Number(card.clueStrength) || 1)) }] : []; }).slice(0, 2) : [];
  if (mode === 'hints') return { ...result, region: '', candidates: [], strongClues: [], weakClues: [], contradictions: [], confusions: [], nextThingsToInspect: result.nextThingsToInspect.filter(safe), coreCard: undefined, extraCards: [] };
  if (mode === 'clue-safe') return { ...result, region: '', description: result.description && safe(result.description) ? result.description : undefined, candidates: [], strongClues: result.strongClues.filter(safe), weakClues: result.weakClues.filter(safe), contradictions: result.contradictions.filter(safe), confusions: [], nextThingsToInspect: result.nextThingsToInspect.filter(safe), coreCard: undefined, extraCards: [] };
  if (mode === 'clue') return { ...result, coreCard: undefined, extraCards: [] }; if (mode === 'explain') return { ...result, region: '', locationEstimate: undefined, candidates: [] }; return result;
}
function base64(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); let binary = ''; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }
async function streetView(view: unknown, headingOffset = 0): Promise<Frame> {
  const key = Deno.env.get('GOOGLE_MAPS_API_KEY') || ''; if (!key) throw new Error('Street View server key is not configured.'); if (!view || typeof view !== 'object') throw new Error('Current Street View orientation is unavailable.'); const item = view as Record<string, unknown>; const pano = String(item.panoId || ''); const heading = Number(item.heading); const pitch = Number(item.pitch); const zoom = Number(item.zoom); if (!pano || ![heading, pitch, zoom].every(Number.isFinite)) throw new Error('Current Street View orientation is invalid.');
  const query = new URLSearchParams({ size: '640x480', pano, heading: String((heading + headingOffset + 360) % 360), pitch: String(Math.max(-90, Math.min(90, pitch))), fov: String(Math.max(25, Math.min(100, 180 / 2 ** zoom))), key }); const response = await fetch(`https://maps.googleapis.com/maps/api/streetview?${query}`, { signal: AbortSignal.timeout(8_000) }); if (!response.ok) throw new Error(`Street View capture failed (${response.status}).`); const mimeType = response.headers.get('content-type')?.split(';')[0] || ''; if (!mimeType.startsWith('image/')) throw new Error('Street View capture returned no image.'); return { mimeType, imageData: base64(await response.arrayBuffer()) };
}
async function gemini(mode: Mode, frames: Frame[], known: Record<string, unknown> | undefined, language: string) {
  if (!keyStates.length) throw new Error('Gemini keys are not configured.'); const models = (Deno.env.get('GEMINI_COACH_MODELS') || 'gemini-2.5-flash-lite,gemini-2.5-flash').split(','); let last = new Error('Gemini Coach is unavailable.');
  for (const model of models) for (let attempt = 0; attempt < Math.min(3, keyStates.length); attempt++) { const state = keyStates[keyCursor++ % keyStates.length]; if (state.cooldownUntil > Date.now()) continue; try { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model.trim())}:generateContent`, { method: 'POST', signal: AbortSignal.timeout(mode === 'analyze360' ? 20_000 : 12_000), headers: { 'content-type': 'application/json', 'x-goog-api-key': state.key }, body: JSON.stringify({ systemInstruction: { parts: [{ text: rules }] }, contents: [{ role: 'user', parts: [{ text: instruction(mode, language, known) }, ...frames.map((frame) => ({ inlineData: { mimeType: frame.mimeType, data: frame.imageData } }))] }], generationConfig: { temperature: .25, maxOutputTokens: 1000, thinkingConfig: { thinkingBudget: 0 }, responseMimeType: 'application/json', responseSchema: schema } }) }); if (response.status === 429) { state.cooldownUntil = Date.now() + 60_000; last = new Error('Gemini quota exceeded.'); continue; } if (!response.ok) { last = new Error(response.status >= 500 ? 'Gemini service error.' : 'Gemini request was rejected.'); continue; } const raw = await response.json(); const text = raw.candidates?.[0]?.content?.parts?.find((part: { text?: string }) => part.text)?.text; if (!text) throw new Error('Gemini returned an empty response.'); return { analysis: normalize(JSON.parse(text), mode, String(known?.actualCountry || '')), model: model.trim(), generatedAt: Date.now() }; } catch (error) { last = error instanceof Error && error.name === 'TimeoutError' ? new Error('Gemini request timed out.') : error as Error; } } throw last;
}

Deno.serve(async (request) => {
  const origin = request.headers.get('origin'); if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: cors(origin) }); if (request.method !== 'POST') return json({ error: 'Method not allowed.' }, 405, origin);
  try { const value = await request.json() as Record<string, unknown>; if (JSON.stringify(value).length > 12_000_000) throw new Error('Screenshot is too large.'); if (value.mode === 'capture') { const frame = await streetView(value.view); return json({ imageDataUrl: `data:${frame.mimeType};base64,${frame.imageData}` }, 200, origin); } const mode = value.mode as Mode; if (!modes.has(mode)) throw new Error('Invalid Coach request.'); const supplied = ['image/jpeg', 'image/png', 'image/webp'].includes(String(value.mimeType)) && /^[A-Za-z0-9+/=]+$/.test(String(value.imageData || '')); const frames = supplied ? [{ mimeType: String(value.mimeType), imageData: String(value.imageData) }] : mode === 'analyze360' ? await Promise.all([0, 90, 180, 270].map((offset) => streetView(value.view, offset))) : [await streetView(value.view)]; const language = Object.hasOwn(languages, String(value.language)) ? String(value.language) : 'en'; const known = ['hints', 'analyze', 'clue', 'clue-safe'].includes(mode) ? undefined : context(value.context); return json(await gemini(mode, frames, known, language), 200, origin); } catch (error) { const message = error instanceof Error ? error.message : 'Coach unavailable.'; return json({ error: message }, /timed out/i.test(message) ? 504 : /quota|cooling/i.test(message) ? 429 : 503, origin); }
});
