import { useState } from 'react';
import { COUNTRIES } from '../data/countries';
import type { Attempt, ReviewRecord, StudyVisit, SupportedLanguage, TrainerLocation, TrainingSession } from '../types';
import { coverageByContinent, exposurePerformance, regionConfusions, retentionAndLapses, sessionStatistics } from '../analytics/advanced';
import { confusions, reviewAnalytics } from '../analytics/statistics';
import { countryDisplayName, translate } from '../services/language';
import { useLanguagePreferences } from '../services/useLanguagePreferences';
import { CountryFlag } from './CountryFlag';
import { pageBounds, timestampRange } from './trainerHubUtils';
import { sortRows, type SortDirection } from '../analytics/tableSorting';
import { ArrowUpRight } from 'lucide-react';

const name = (code: string, locale: SupportedLanguage) => countryDisplayName(code, locale) || COUNTRIES[code]?.name || code;
const pct = (value: number | null) => value === null ? '—' : `${Math.round(value * 100)}%`;
const num = (value: number | null, locale: SupportedLanguage) => value === null ? '—' : Math.round(value).toLocaleString(locale);
const duration = (seconds: number) => seconds < 3600 ? `${Math.round(seconds / 60)}m` : `${Math.floor(seconds / 3600)}h ${Math.round(seconds % 3600 / 60)}m`;

export function ReviewStatistics({ attempts, reviews }: { attempts: Attempt[]; reviews: ReviewRecord[] }) {
  const { ui } = useLanguagePreferences(); const t = (key: string) => translate(ui, key);
  const [page, setPage] = useState(1);
  const [countryLapsePage, setCountryLapsePage] = useState(1); const [locationLapsePage, setLocationLapsePage] = useState(1);
  const data = reviewAnalytics(attempts, reviews);
  const improvements = data.improvements.slice().reverse(); const paging = pageBounds(improvements.length, page, 10);
  const learning = retentionAndLapses(attempts);
  const today = new Date().setHours(0, 0, 0, 0);
  const week = today - 6 * 86400000;
  const reviewAttempts = attempts.filter((item) => item.source === 'review');
  const attemptByPano = new Map(attempts.map((item) => [item.panoId, item]));
  const countryLapsePaging = pageBounds(learning.lapseCountries.length, countryLapsePage, 10); const locationLapsePaging = pageBounds(learning.lapseLocations.length, locationLapsePage, 10);
  const pager = (paging: ReturnType<typeof pageBounds>, setCurrentPage: (page: number) => void, label: string) => paging.pages > 1 && <nav className="clue-pagination" aria-label={label}><button type="button" disabled={paging.current === 1} onClick={() => setCurrentPage(paging.current - 1)}>{t('Previous')}</button><span aria-live="polite">{paging.current} / {paging.pages}</span><button type="button" disabled={paging.current === paging.pages} onClick={() => setCurrentPage(paging.current + 1)}>{t('Next')}</button></nav>;
  return <>
    <div className="metric-strip"><div><span>{t('Today')}</span><strong>{reviewAttempts.filter((item) => item.createdAt >= today).length}</strong></div><div><span>{t('7 days')}</span><strong>{reviewAttempts.filter((item) => item.createdAt >= week).length}</strong></div><div><span>{t('All time')}</span><strong>{data.completed}</strong></div><div><span>{t('Due')}</span><strong>{data.due}</strong></div><div><span>{t('Locations')}</span><strong>{data.locations}</strong></div><div><span>{t('Avg improvement')}</span><strong>{num(data.averageImprovement, ui)}</strong><small>n={data.eligible}</small></div></div>
    <div className="stats-callouts"><span>{t('Improved')} <b>{data.improved}</b></span><span>{t('Country corrected')} <b>{data.corrected}</b></span>{Object.entries(data.gradeCounts).map(([grade, count]) => <span key={grade}>{t(grade)} <b>{count}</b></span>)}</div>
    <section><h3>{t('Retention')}</h3><div className="stats-callouts">{learning.retention.map((item) => <span key={item.days}>{item.days}d <b>{item.eligible >= 5 ? pct(item.rate) : t('Low sample')}</b><small> n={item.eligible}</small></span>)}</div></section>
    <section><h3>{t('Review improvement history')}</h3><div className="table-scroll"><table><thead><tr><th>{t('Date')}</th><th>{t('Country')}</th><th>{t('Before')}</th><th>{t('Review')}</th><th>{t('Score Δ')}</th><th>{t('Distance gain')}</th><th>{t('Time Δ')}</th></tr></thead><tbody>{improvements.slice(paging.start, paging.end).map((item) => <tr key={item.attempt.id}><td>{new Date(item.attempt.createdAt).toLocaleDateString(ui)}</td><th><CountryFlag code={item.attempt.countryCode} />{name(item.attempt.countryCode, ui)}</th><td>{item.original.score.toLocaleString(ui)}</td><td>{item.attempt.score.toLocaleString(ui)}</td><td>{item.score > 0 ? '+' : ''}{item.score.toLocaleString(ui)}</td><td>{item.distance === null ? '—' : `${item.distance > 0 ? '+' : ''}${Math.round(item.distance).toLocaleString(ui)} km`}</td><td>{item.attempt.timeSpentSeconds - item.original.timeSpentSeconds}s</td></tr>)}</tbody></table></div>{paging.pages > 1 && <nav className="clue-pagination" aria-label={t('Review improvement history')}><button type="button" disabled={paging.current === 1} onClick={() => setPage(paging.current - 1)}>{t('Previous')}</button><span aria-live="polite">{paging.current} / {paging.pages}</span><button type="button" disabled={paging.current === paging.pages} onClick={() => setPage(paging.current + 1)}>{t('Next')}</button></nav>}</section>
    <div className="stats-ladders"><section className="stats-card"><h3>{t('Lapsed countries')}</h3>{learning.lapseCountries.slice(countryLapsePaging.start, countryLapsePaging.end).map((item) => <div className="data-row" key={item.key}><span><CountryFlag code={item.key} />{name(item.key, ui)}</span><b>{item.count}</b></div>)}{!learning.lapseCountries.length && <p className="empty">{t('No learned-to-wrong review transitions yet.')}</p>}{pager(countryLapsePaging, setCountryLapsePage, t('Lapsed countries'))}</section><section className="stats-card"><h3>{t('Lapsed locations')}</h3>{learning.lapseLocations.slice(locationLapsePaging.start, locationLapsePaging.end).map((item) => { const attempt = attemptByPano.get(item.key); return <div className="data-row" key={item.key}><span>{attempt ? <><CountryFlag code={attempt.countryCode} />{name(attempt.countryCode, ui)}</> : t('Unknown location')}</span><b>{item.count}</b><a className="icon-button" href={`https://www.google.com/maps/@?api=1&map_action=pano&pano=${encodeURIComponent(item.key)}`} target="_blank" rel="noreferrer" aria-label={t('openLocation')}><ArrowUpRight size={15} /></a></div>; })}{!learning.lapseLocations.length && <p className="empty">{t('No location lapses yet.')}</p>}{pager(locationLapsePaging, setLocationLapsePage, t('Lapsed locations'))}</section></div>
  </>;
}

export function ConfusionStatistics({ attempts, onTrainCountries }: { attempts: Attempt[]; onTrainCountries: (codes: string[], name: string) => void }) {
  const { ui } = useLanguagePreferences(); const t = (key: string) => translate(ui, key);
  const [directionalPage, setDirectionalPage] = useState(1); const [symmetricPage, setSymmetricPage] = useState(1); const [regionPage, setRegionPage] = useState(1);
  const country = confusions(attempts); const regions = regionConfusions(attempts);
  const pager = (paging: ReturnType<typeof pageBounds>, setPage: (page: number) => void, label: string) => paging.pages > 1 && <nav className="clue-pagination" aria-label={label}><button type="button" disabled={paging.current === 1} onClick={() => setPage(paging.current - 1)}>{t('Previous')}</button><span aria-live="polite">{paging.current} / {paging.pages}</span><button type="button" disabled={paging.current === paging.pages} onClick={() => setPage(paging.current + 1)}>{t('Next')}</button></nav>;
  const list = (title: string, items: typeof country.directional, symbol: string, page: number, setPage: (page: number) => void) => { const paging = pageBounds(items.length, page, 10); return <section className="stats-card"><h3>{t(title)}</h3>{items.slice(paging.start, paging.end).map((item) => <button className="data-row" key={item.codes.join(':')} onClick={() => onTrainCountries(item.codes, t('Confusion drill'))}><span><CountryFlag code={item.codes[0]} />{name(item.codes[0], ui)} {symbol} <CountryFlag code={item.codes[1]} />{name(item.codes[1], ui)}</span><b>{item.count}</b></button>)}{!items.length && <p className="empty">{t('No resolved country confusions yet.')}</p>}{pager(paging, setPage, t(title))}</section>; };
  const regionPaging = pageBounds(regions.length, regionPage, 10);
  return <><div className="stats-ladders">{list('Directional', country.directional, '→', directionalPage, setDirectionalPage)}{list('Symmetric', country.symmetric, '↔', symmetricPage, setSymmetricPage)}</div><section className="stats-card"><h3>{t('Region confusions')}</h3>{regions.slice(regionPaging.start, regionPaging.end).map((item) => <div className="data-row" key={item.pair}><span>{item.pair}</span><b>{item.count}</b></div>)}{!regions.length && <p className="empty">{t('No resolved region confusions yet.')}</p>}{pager(regionPaging, setRegionPage, t('Region confusions'))}</section></>;
}

export function CoverageStatistics({ locations, visits, attempts, includeAssisted = false }: { locations: TrainerLocation[]; visits: StudyVisit[]; attempts: Attempt[]; includeAssisted?: boolean }) {
  const { ui } = useLanguagePreferences(); const t = (key: string) => translate(ui, key);
  const [coverageSort, setCoverageSort] = useState<'continent' | 'seen' | 'supported' | 'coverage'>('continent'); const [coverageDirection, setCoverageDirection] = useState<SortDirection>('asc');
  const [exposureSort, setExposureSort] = useState<'country' | 'exposures' | 'studySeconds' | 'revealed' | 'played' | 'accuracy' | 'sample'>('exposures'); const [exposureDirection, setExposureDirection] = useState<SortDirection>('desc');
  const seen = new Set(locations.map((item) => item.countryCode));
  const coverage = coverageByContinent(locations); const exposure = exposurePerformance(visits, attempts, includeAssisted);
  const sortedCoverage = sortRows(coverage, (item) => ({ continent: t(item.continent), seen: item.seen, supported: item.supported, coverage: item.seen / item.supported }[coverageSort]), coverageDirection);
  const sortedExposure = sortRows(exposure, (item) => ({ country: name(item.code, ui), exposures: item.exposures, studySeconds: item.studySeconds, revealed: item.revealed, played: item.played, accuracy: item.accuracy.rate, sample: item.accuracy.eligible }[exposureSort]), exposureDirection);
  const header = <T extends string>(key: T, active: T, direction: SortDirection, setKey: (value: T) => void, setDirection: (value: SortDirection) => void, label: string) => <th aria-sort={active === key ? direction === 'asc' ? 'ascending' : 'descending' : 'none'}><button type="button" className="sortable-heading" onClick={() => { if (active === key) setDirection(direction === 'asc' ? 'desc' : 'asc'); else { setKey(key); setDirection('asc'); } }} aria-label={`${t('Sort by')}: ${label}`}>{label}{active === key ? ` ${direction === 'asc' ? '↑' : '↓'}` : ''}</button></th>;
  return <><div className="metric-strip"><div><span>{t('Supported')}</span><strong>{Object.keys(COUNTRIES).length}</strong></div><div><span>{t('Countries seen')}</span><strong>{seen.size}</strong></div><div><span>{t('Never seen')}</span><strong>{Object.keys(COUNTRIES).length - seen.size}</strong></div><div><span>{t('Unique panoramas')}</span><strong>{locations.length}</strong></div><div><span>{t('Coverage')}</span><strong>{pct(seen.size / Object.keys(COUNTRIES).length)}</strong></div></div>
    <section><h3>{t('Coverage by continent')}</h3><div className="table-scroll"><table><thead><tr>{header('continent', coverageSort, coverageDirection, setCoverageSort, setCoverageDirection, t('Continent'))}{header('seen', coverageSort, coverageDirection, setCoverageSort, setCoverageDirection, t('Seen'))}{header('supported', coverageSort, coverageDirection, setCoverageSort, setCoverageDirection, t('Supported'))}{header('coverage', coverageSort, coverageDirection, setCoverageSort, setCoverageDirection, t('Coverage'))}</tr></thead><tbody>{sortedCoverage.map((item) => <tr key={item.continent}><th>{t(item.continent)}</th><td>{item.seen}</td><td>{item.supported}</td><td>{pct(item.seen / item.supported)}</td></tr>)}</tbody></table></div></section>
    <section><h3>{t('Study exposure vs Play performance')}</h3><p className="stats-note">{t('Descriptive only; exposure does not prove causation.')}</p><div className="table-scroll"><table><thead><tr>{header('country', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Country'))}{header('exposures', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Study scenes'))}{header('studySeconds', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Study time'))}{header('revealed', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Revealed'))}{header('played', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Play'))}{header('accuracy', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Accuracy'))}{header('sample', exposureSort, exposureDirection, setExposureSort, setExposureDirection, t('Sample'))}</tr></thead><tbody>{sortedExposure.map((item) => <tr key={item.code}><th><CountryFlag code={item.code} />{name(item.code, ui)}</th><td>{item.exposures}</td><td>{duration(item.studySeconds)}</td><td>{item.revealed}</td><td>{item.played}</td><td>{pct(item.accuracy.rate)}</td><td>{item.accuracy.eligible}</td></tr>)}</tbody></table></div></section>
  </>;
}

export function SessionStatistics({ sessions, attempts, visits, includeAssisted = false }: { sessions: TrainingSession[]; attempts: Attempt[]; visits: StudyVisit[]; includeAssisted?: boolean }) {
  const { ui } = useLanguagePreferences(); const t = (key: string) => translate(ui, key);
  const [page, setPage] = useState(1);
  const data = sessionStatistics(sessions, attempts, visits, includeAssisted);
  const paging = pageBounds(data.rows.length, page, 10);
  return <><div className="metric-strip"><div><span>{t('Sessions')}</span><strong>{data.rows.length}</strong></div><div><span>{t('Total active')}</span><strong>{duration(data.rows.reduce((sum, item) => sum + item.activeTimeSeconds, 0))}</strong></div><div><span>{t('Longest')}</span><strong>{duration(Math.max(0, ...data.rows.map((item) => item.activeTimeSeconds)))}</strong></div><div><span>{t('Best eligible')}</span><strong>{data.bestAccuracy?.accuracy.eligible >= 10 ? pct(data.bestAccuracy.accuracy.rate) : '—'}</strong></div><div><span>{t('Most reviews')}</span><strong>{data.mostReviews?.reviews || 0}</strong></div><div><span>{t('Fastest ≥70%')}</span><strong>{data.fastestAccurate ? duration(data.fastestAccurate.activeTimeSeconds) : '—'}</strong></div></div>
    <div className="attempt-list">{data.rows.slice(paging.start, paging.end).map((item) => <div className="attempt-row session-row" key={item.id}><span><strong>{timestampRange(item.startedAt, item.endedAt, ui)}</strong><small>{duration(item.activeTimeSeconds)} · {item.countries} {t('countries')}</small></span><span>{item.study} {t('Study')} · {item.play} {t('Play')} · {item.reviews} {t('Review')}</span><strong>{pct(item.accuracy.rate)} <small>n={item.accuracy.eligible}</small></strong><span>{t('Avg score')} {num(item.averageScore, ui)}</span></div>)}</div>
    {paging.pages > 1 && <nav className="clue-pagination" aria-label={t('Sessions')}><button type="button" disabled={paging.current === 1} onClick={() => setPage(paging.current - 1)}>{t('Previous')}</button><span aria-live="polite">{paging.current} / {paging.pages}</span><button type="button" disabled={paging.current === paging.pages} onClick={() => setPage(paging.current + 1)}>{t('Next')}</button></nav>}
  </>;
}
