import { useMemo, useState } from 'react';
import { Eye, MapPin, Search, Trash2, X } from 'lucide-react';
import type { ClueRecord } from '../types';
import { COUNTRIES } from '../data/countries';
import { CountryFlag } from './CountryFlag';
import { ClueGallery } from './ClueGallery';
import { countryName, useHubTranslate } from './trainerHubUtils';

type ClueView = 'library' | 'countries' | 'insights';

export function TrainerHubClues({ clues, onDelete, onTrainCountries }: { clues: ClueRecord[]; onDelete: (id: string) => void; onTrainCountries: (codes: string[], name: string) => void }) {
  const t = useHubTranslate(); const [view, setView] = useState<ClueView>('library'); const [query, setQuery] = useState(''); const [country, setCountry] = useState(''); const [gallery, setGallery] = useState<{ country: string; clueId?: string } | null>(null);
  const filtered = useMemo(() => clues.filter((clue) => (!country || clue.countryCode === country) && (!query || `${countryName(clue.countryCode)} ${clue.analysis.description} ${clue.analysis.strongClues.join(' ')}`.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => b.createdAt - a.createdAt), [clues, country, query]);
  const groups = useMemo(() => [...new Set(clues.map((clue) => clue.countryCode))].map((code) => { const rows = clues.filter((clue) => clue.countryCode === code); return { code, count: rows.length, latest: Math.max(...rows.map((row) => row.createdAt)), confidence: rows.reduce((sum, row) => sum + (row.analysis.candidates[0]?.confidence || 0), 0) / rows.length }; }).sort((a, b) => b.count - a.count || countryName(a.code).localeCompare(countryName(b.code))), [clues]);
  const analyzed = clues.filter((clue) => clue.analysis.candidates.length).length; const averageConfidence = analyzed ? clues.reduce((sum, clue) => sum + (clue.analysis.candidates[0]?.confidence || 0), 0) / analyzed : 0;
  const streetViewUrl = (clue: ClueRecord) => `https://www.google.com/maps/@?api=1&map_action=pano&pano=${encodeURIComponent(clue.panoId)}`;
  return <section className="clues-panel">
    <div className="statistics-title"><div><h2>{t('Clues')}</h2><p>{t('Your saved visual clues, organized for study.')}</p></div><nav>{(['library', 'countries', 'insights'] as ClueView[]).map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{t(item === 'library' ? 'Library' : item === 'countries' ? 'Countries' : 'Insights')}</button>)}</nav></div>
    <div className="metric-strip"><div><span>{t('Saved clues')}</span><strong>{clues.length}</strong></div><div><span>{t('Countries covered')}</span><strong>{groups.length}</strong></div><div><span>{t('Analyzed')}</span><strong>{analyzed}</strong></div><div><span>{t('Average confidence')}</span><strong>{Math.round(averageConfidence * 100)}%</strong></div></div>
    {view === 'library' && <><div className="clue-tools"><label><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('Search clues')} /></label><div className="clue-country-filter"><select aria-label={t('Countries')} value={country} onChange={(event) => setCountry(event.target.value)}><option value="">{t('allCountries')}</option>{groups.map((group) => <option key={group.code} value={group.code}>{countryName(group.code)} ({group.count})</option>)}</select>{country && <button className="icon-button" onClick={() => setCountry('')} aria-label={t('clearCountryFilter')} title={t('clearCountryFilter')}><X size={16} /></button>}</div></div><div className="clue-library">{filtered.map((clue) => <article key={clue.id} role="button" tabIndex={0} onClick={() => setGallery({ country: clue.countryCode, clueId: clue.id })} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setGallery({ country: clue.countryCode, clueId: clue.id }); } }}><img src={clue.imageDataUrl} alt={t('savedVisualClue')} /><div><h3><CountryFlag code={clue.countryCode} />{countryName(clue.countryCode)}</h3><p>{clue.analysis.description || clue.analysis.strongClues[0] || t('savedVisualClue')}</p><small>{new Date(clue.createdAt).toLocaleDateString()}</small></div><div><button className="icon-button" onClick={(event) => { event.stopPropagation(); setGallery({ country: clue.countryCode, clueId: clue.id }); }} aria-label={t('Details')}><Eye size={16} /></button><a className="icon-button" href={streetViewUrl(clue)} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()} aria-label={t('Reopen clue location')}><MapPin size={16} /></a><button className="icon-button" onClick={(event) => { event.stopPropagation(); onDelete(clue.id); }} aria-label={t('deleteClue')}><Trash2 size={16} /></button></div></article>)}{!filtered.length && <p className="empty">{t('No saved clues yet. Analyze a scene to build your library.')}</p>}</div></>}
    {view === 'countries' && <div className="table-scroll"><table><thead><tr><th>{t('Country')}</th><th>{t('Saved clues')}</th><th>{t('Average confidence')}</th><th>{t('Latest')}</th><th /></tr></thead><tbody>{groups.map((group) => <tr key={group.code}><td><CountryFlag code={group.code} />{countryName(group.code)}</td><td>{group.count}</td><td>{Math.round(group.confidence * 100)}%</td><td>{new Date(group.latest).toLocaleDateString()}</td><td><button className="review-location-button" onClick={() => onTrainCountries([group.code], countryName(group.code))}>{t('Practice')}</button></td></tr>)}</tbody></table></div>}
    {view === 'insights' && <div className="clue-insights"><p>{t('Confidence reflects the Coach estimate, not a verified answer.')}</p>{groups.slice(0, 8).map((group) => <button key={group.code} onClick={() => { setCountry(group.code); setView('library'); }}><span><CountryFlag code={group.code} />{countryName(group.code)}</span><strong>{group.count}</strong></button>)}</div>}
    {gallery && <ClueGallery country={countryName(gallery.country)} clues={clues.filter((clue) => clue.countryCode === gallery.country)} initialSelectedId={gallery.clueId} onClose={() => setGallery(null)} onDelete={onDelete} />}
  </section>;
}
